### ISSUE TITLE
Getting Money

### ISSUE THREAD

**Issue by amstan** [aichallenge/aichallenge#10]
j3camero is responsible for this. He will go around shaking his tin cup with potential sponsors, with right of first refusal going to our generous sponsor from past contests, Google. He also has to perhaps register us as a non-profit corporation so that he does not incur personal income tax liability when sponsors give him money.

**Comment by jeremyroman** [comment]
Be aware that there is a lot of complexity associated with incorporation (even not-for-profit).
http://www.ic.gc.ca/eic/site/cd-dgc.nsf/eng/cs03440.html

Requires at least three directors, all of whom are 18 years of ago (and in Canada, I think), requires annual meetings

And of course, the corporation name should not include any registered trademarks (most notably Google's).

There may be a path of less resistance (maybe a tax accountant or something would have insight; I'm not sure).

**Comment by j3camero** [comment]
Awesome thanks Jeremy. I will try to set us up some corporate goodness.

We need three officers in Canada you say? We should invent three ridiculous titles for fun.

**Comment by jeremyroman** [comment]
At least three directors. The directors may or may not be officers. There's a number of things you have to define about corporate structure if you want to do this.

If lazy, you can go with the Corporations Canada model by-laws, which includes provisions for:
- elected board of directors
- appointed members
- 4+ officers (President, Vice-President, Secretary, Treasurer, and optionally more) who may or may not be the same people
- etc

(The biggest annoyance with the model by-laws is that it specifies that contracts require the signature of two officers.)

**Comment by amstan** [comment]
This isn't a launch issue, relabeling.

**Comment by McLeopold** [comment]
OMG! JEFF! WHERE ARE YOU!

**Comment by amstan** [comment]
Sent him a text, He might appear sometime.

**Comment by mleise** [comment]
This issue is closed, I've heard!
