### ISSUE TITLE
Visualizer Wish List

### ISSUE THREAD

**Issue by McLeopold** [aichallenge/aichallenge#101]
This is list of things I think would be nice for the visualizer.  Feel free to add comments to this issue and we can discuss what is important/feasible.
- The contrast between land and water is very high.  This makes watching the ant battle hard because you can really only see the landscape and not the ants moving around.  I think the land/water contrast should be very slight so it fades away compared to the individual ants.
- It would be cool if the graph of ants over time could be switched between the actual and the percentage.  Also, by clicking the scores/ants sections above the graph could be switched between the 2.
- The top score and ants graphs could slide between the different values when animating.  Right now it is choppy.
- The wrapped view should be the default, not the border view.
- When clicking a fog of war view, if in wrapped view, the map should slide to center on that bots starting location.  Or perhaps a secondary button for centering.  (Of course when I produce multiple start maps, this gets hard.)
- When clicking on an individual ant, get a map of that ants movements throughout the game with a marker for the spawn and death spots.  This could be similar to the fog overlays.
- When paused and clicking/hovering on an individual ant, highlight the ants it damages and the ants that damage it and give values for each.  A simple circle of the attack radius would be a big improvement, but the values for taking damage are different for each ant and more complicated to calculate.
- Allow for modifying the playback speed.

**Comment by mleise** [comment]
Ok, I'll just add my own whish list here.
- info button showing a message box with game meta data not visible otherwise (attack radius, timers, ...)
- zoom in to 20x20 squares with animated ants like it used to be in the early days
- functionality to set cpu usage to something different than 50%
- keep a minimum size to allow the controls to render
- show when a bot crashed, timed out, was defeated (display icons in the graph)
- hyperlink button to original game if game_url is given

**Comment by mleise** [comment]
I had the scores/ant section animated. I found the font rendering to be rather slow and since I implemented antimatroid's idea of animated half-steps using the buttons below the map area it looks pretty confusing if the values change mid-turn. The animation looked great otherwise.

**Comment by McLeopold** [comment]
What about ant trails?  Is that possible?

**Comment by mleise** [comment]
That is possible with a moderate amount of work. Maybe I'll add that on mouse over. The annoying bit is always the wrapping of parts of the graphics. Sometimes I wish I made everything graphics objects with bounding boxes so the drawing function would not contain so much wrapping and coordinate correction code.

**Comment by McLeopold** [comment]
We've made mleise do enough for now.  He can be free to have a snack.
