### ISSUE TITLE
Archiving old contests

### ISSUE THREAD

**Issue by amstan** [aichallenge/aichallenge#11]
I would like to make sure the old contests remain uploaded and all the info from them accessible. Ideally in a ai-contest.com subdomain.

How should this be done? A static html copy of everything? A read only php thing with everything disabled(that still uses the mysql database)?

**Comment by jeremyroman** [comment]
I like the idea of a plain static copy – it means that we don't have to maintain software or keep old databases operational.

**Comment by amstan** [comment]
How do you propose we make such a static copy? I haven't had good experiences with wget on this.
Also.. will wget go and get the api call for the visualizers? It would be nice to have the visualizers operational too.

**Comment by jeremyroman** [comment]
Visualizers might require more thought, depending on how they fetch their data. I know that there exist static archival tools. If it proves too difficult, a dynamic archive would of course be the fallback.

**Comment by DanielVF** [comment]
+1 for static. 

We could strip down the templates a little before archiving. Slap the static copy up on Amazon S3 and be done with it till the end of time.

**Comment by amstan** [comment]
j3camero: I hope you still have the db for this site: http://csclub.uwaterloo.ca/~j3camero/contest/fall2009/results.php

It used to work for a while.

**Comment by ahmedhelal** [comment]
I have found a method to download all the data from the old website including visualizers, already mentioned it on the irc, and will post the results once am done.

**Comment by amstan** [comment]
You haven't told us what you're using yet. Have you went around the duplication of all the css files and js files?

**Comment by amstan** [comment]
Well.. this is done. Except for RPS.
