### ISSUE TITLE
Bug in game engine - missing info about own dead ant

### ISSUE THREAD

**Issue by sir-macelon** [aichallenge/aichallenge#111]
The game engine is not sending info about player's own dead ants if this player loses visibility over the tile where his ant died.

**Comment by McLeopold** [comment]
This has been discussed on IRC and we agree it should be implemented.  The vision for a turn should be based on what you could see before the attack phase plus what you can see after the birth/spawn phase.

**Comment by amstan** [comment]
Isn't this done? @Mcleopold

**Comment by McLeopold** [comment]
No, and I think sigh is unavailable for awhile.  This can be done after beta.  It's not a show stopper.

**Comment by sigh** [comment]
I've added a special case for dead ants. Being able to see _everything_ from before the attack phase complicates the code a bit (and slows it down), so if there is significant support for it then it would be good if the rationale for that was documented here. (I know at least antimatroid disagrees with it).

Anyway, I don't quite know the status of all this and I'm a bit out of the loop on this stuff, so I'm not closing the issue.

**Comment by McLeopold** [comment]
The rational is that if you send a scout somewhere, you should be able to see what the scout saw.  If the scout died in a battle, you should be able to see the results of that battle.  A bot should always be able to see the outcome if its own actions.

The code should calculate vision based on live and dead ants after move and attack phases.  This would only involve splitting the update vision function into 2 parts, vision after move, vision after death.

**Comment by sigh** [comment]
What about ants which die _during_ the move (ie collisions)?

**Comment by McLeopold** [comment]
I would say they still get to see what was seen before the collision.  Could we start with a vision matrix at the beginning of a turn and update it for every ant move, even if it was to a collision?  The first ant to the same spot should be enough to update it.

**Comment by McLeopold** [comment]
Due to a lack of interest in the feature, and that fact that we don't have time to code it, I will say the specs should indicate dead ants don't get to report vision back.
