### ISSUE TITLE
common_lisp starter bot does not conform to standard

### ISSUE THREAD

**Issue by McLeopold** [aichallenge/aichallenge#112]
The starter bots should not have tools. Starter bots need to have at least a MyBot.ext file in the root dir; For lisp this would be MyBot.lisp. Makefiles will not be used for official compilation, although they can be included.  Currently the zipped archive of the common_lisp folder does not compile when uploaded to a test server.

**Comment by aerique** [comment]
https://github.com/aichallenge/aichallenge/commit/cf2ad19e55dd0a81ff10c96332da5439159e17a1
