### ISSUE TITLE
Scheme Starter Package

### ISSUE THREAD

**Issue by DanielCollins** [aichallenge/aichallenge#12]
Implement support for the scheme programming language. An incomplete  list of scheme implementations may be found on this page: http://community.schemewiki.org/?scheme-faq-standards. The author personally recommends, in descending order, ikarus, MIT/GNU scheme or plt-r6rs (part of racket) as having the best combination of useful features and performance, but you will probably find that scheme programmers are willing to adapt to whatever implementation is at hand.

**Comment by DanielCollins** [comment]
Should someone either implement the above request, or come to a final and guaranteed decision regarding its implementation, I would be happy to implement a scheme "starter package". GitHub mail 'PurplePanda' or talk to 'pyro-' on irc.freenode.net if you want.

**Comment by amstan** [comment]
As j3camero said the other day:
- We can have multiple scheme implementations(mit-scheme, racket)
- We should have racket available

So I suggest making both of them(racket and mit-scheme), if you want.

Do not worry, your work will not go wasted.

**Comment by amstan** [comment]
How's the scheme starter package going?

**Comment by DanielCollins** [comment]
oh right i was going to make one of those :D i haven't been watching your competition at all since i don't intend to compete anymore. is it open soon? but i recall i had it almost usable when i last left off so i could probably finish it and upload it to my account here reasonably soonish if you want it

**Comment by DanielCollins** [comment]
well i've coded one up git clone git://github.com/PurplePanda/AuntHillary.git . Making it 'good' is a work in progress, i hope i get some free time but it should already be protocol correct. i must figure out how to test it with the actual engine to confirm that.

**Comment by amstan** [comment]
Is this still in progress?

**Comment by DanielCollins** [comment]
Not as far as I know. Although I was the one who opened this issue it has been some time since I held any interest in your competition. If you are asking about server side support then I can't help you. I see that antimatroid is assigned to it, maybe you can ask him. As for my "starter pack", it never got tested on a real server but I thought that it was probably protocol-correct if slow when I last left off. I haven't even glanced at it since the date of my last commit. If therefore there have been any changes to the game, protocol or server configuration in that time I don't know about them and neither does my program. Frankly I would prefer to remain ignorant, but if anyone makes any specific bug reports against my program I will fix them. I recall that there was one other person who was also talking in your freenode channel about writing such a program, but I don't remember their name and I don't know anything else about that.

**Comment by wfi** [comment]
PurplePanda's AuntHillary seems to have disappeared.  I am intending to write a starter package for Racket unless someone points me to a finished or nearly finished alternative.  Thanks!

**Comment by amstan** [comment]
Racket Starter package now available.
