### ISSUE TITLE
Can't change bio or affiliation

### ISSUE THREAD

**Issue by smiley1983** [aichallenge/aichallenge#126]
When I try to change my bio or affiliation, I get "Invalid organization id: 0" in either case.
The profile is named "solifugid", but I get the same errors when I try to edit those things on my test server inside a virtual machine.

**Comment by amstan** [comment]
Seems to work for my profile on aichallengebeta.
Where is this error showing?

**Comment by smiley1983** [comment]
on aichallengebeta, url /save_profile.php
When I try to change the bio, I get a blank white page with "Invalid organization id: 0" at the top left, no other info.
Should I try making another profile to see if it's just that one?

**Comment by smiley1983** [comment]
sorry, didn't mean to close.
I made a profile named "test11", started with blank bio, and then tried to change it - same error

**Comment by amstan** [comment]
This is done right?

**Comment by smiley1983** [comment]
Yes, it's done.
