### ISSUE TITLE
Website pruning

### ISSUE THREAD

**Issue by amstan** [aichallenge/aichallenge#128]
Now that we have the tools ready I can go and delete whatever's left from planet wars. Maybe make some docs for the tools.

After this, the website content should be complete.

**Comment by amstan** [comment]
Pages that need to be rewritten:
- http://aichallengebeta.hypertriangle.com/using_the_tools.php - [moved to wiki page](https://github.com/aichallenge/aichallenge/wiki/Using-the-Tools)
- http://aichallengebeta.hypertriangle.com/starting_your_own.php
- http://aichallengebeta.hypertriangle.com/resources.php
- http://aichallengebeta.hypertriangle.com/simple_strategy_guide.php
- http://aichallengebeta.hypertriangle.com/advanced_strategy_guide.php

Please review my changes

**Comment by aerique** [comment]
I've updated `using_the_tools.php` on the wiki.  I'm not clear whether it's supposed to stay there (I've added explicit links to ai-contest.com in case it does).

`starting_your_own.php` and `simple_strategy_guide.php` are still about Planet Wars.

`resources.php` is fine.

`advanced_strategy_guide.php` is empty and I'm not sure it is needed.

**Comment by amstan** [comment]
`faq.php` contains info about the planet wars.

The pages you mentioned @aerique should also be linked from the wiki.

**Comment by mleise** [comment]
I tried to assemble an up-to-date list.

http://aichallenge.org/starting_your_own.php
Contains PlanetWars content as mentioned above and reported here: http://ai-contest.com/forums/viewtopic.php?f=25&p=9390

http://aichallenge.org/specification.php
This page has no navigation menu in Opera and Chrome.

http://aichallenge.org/strategy_guide.php
Is still incomplete.

http://ai-contest.com/forum/
Could use a new theme for Ants

http://aichallenge.org/faq.php
Info about PlanetWars

http://aichallenge.org/resources.php
Is orphan (not linked from the menu bar) and contains dead links

**Comment by amstan** [comment]
I tried to assemble an up-to-date list.

http://aichallenge.org/faq.php
**Done**

http://aichallenge.org/specification.php
See https://github.com/aichallenge/aichallenge/issues/292

http://ai-contest.com/forum/
See https://github.com/aichallenge/aichallenge/issues/290

http://aichallenge.org/strategy_guide.php
http://aichallenge.org/starting_your_own.php
http://aichallenge.org/resources.php
I see @mcleopold has a project to make new tutorials, i'll leave him reorganize these pages.

**Comment by amstan** [comment]
http://aichallenge.org/strategy_guide.php
Is incomplete

http://aichallenge.org/resources.php
Is orphan

http://aichallenge.org/starting_your_own.php
Got deleted

**Comment by Zannick** [comment]
http://aichallenge.org/country_profile.php
http://aichallenge.org/language_profile.php
http://aichallenge.org/organization_profile.php

are all extremely similar to

http://aichallenge.org/rankings.php

We should move their functionality (limiting the ranking results) into rankings.php. I'll note that this will allow us to see rankings like "C++ users from the United States".
