### ISSUE TITLE
Bug in game engine - 'None' instead of player ID

### ISSUE THREAD

**Issue by sir-macelon** [aichallenge/aichallenge#132]
When a new ant is spawned and gets vision over a tile where an enemy ant died this turn, then the game engine sends something like this: "d <row> <col> None". This line shouldn't be sent at all as the spawned ant wasn't supposed to see this battle resolution anyway, because spawning phase is after battle resolution phase.

**Comment by sir-macelon** [comment]
See game http://aichallengebeta.hypertriangle.com/visualizer.php?game=7779&turn=45&row=96&col=7 as example, bot aerique-test.

**Comment by McLeopold** [comment]
Now that I think about it, it is probably a dead ant of an ilk the player hasn't seen before.  This would be the switch matrix that sets the player numbers for a bots perspective.

**Comment by McLeopold** [comment]
The newly spawned ant will still get to see the dead ant.  This is because I don't want to code for this edge case.  If it is important, convince sigh.

**Comment by sir-macelon** [comment]
It is not important for me. Moreover I don't think anyone would use this information, yet it is a bug and if you want to make it a feature, then you'd better change the game spec for people to be aware of it.
