### ISSUE TITLE
Testing of starter packages

### ISSUE THREAD

**Issue by Hjax** [aichallenge/aichallenge#136]
Place holder for testing of starter packages

Python -  the bot works fine, runs exactly as it should with a good description

**Comment by aerique** [comment]
What does your testing process look like?  I might have some time to test some of the starter packages as well.

**Comment by amstan** [comment]
I want them uploaded on the site, check their behavior against the python bot (they shouldn't be too smart).

If they error, test them locally with a test_bot.sh, note the error somewhere. Have a go at fixing it, if it's too complicated use `git blame`(on github: button on top right) to find the guy who wrote it and contact him (tell him about the test server). An issue wouldn't hurt either.

**Comment by amstan** [comment]
How's this going?

**Comment by aerique** [comment]
Most of the starter bots are running on the beta server by names of <language>starterbot.  So unless any have them have issues I'd say it is going well.

Issue 187 would be handy for checking the bots in this regard: https://github.com/aichallenge/aichallenge/issues/187

Might as well list them:
- C++: http://aichallengebeta.hypertriangle.com/profile.php?user=132
- C#: http://aichallengebeta.hypertriangle.com/profile.php?user=87
- CoffeeScript: http://aichallengebeta.hypertriangle.com/profile.php?user=54
- Common Lisp: http://aichallengebeta.hypertriangle.com/profile.php?user=89
- D: http://aichallengebeta.hypertriangle.com/profile.php?user=52
- Go: http://aichallengebeta.hypertriangle.com/profile.php?user=56
- Java: http://aichallengebeta.hypertriangle.com/profile.php?user=58
- Perl: http://aichallengebeta.hypertriangle.com/profile.php?user=83
- PHP: http://aichallengebeta.hypertriangle.com/profile.php?user=53
- Python: http://aichallengebeta.hypertriangle.com/profile.php?user=55
- Ruby: http://aichallengebeta.hypertriangle.com/profile.php?user=57

Missing: C, Haskell, JavaScript, LOLCODE, OCaml & Scala.

**Comment by McLeopold** [comment]
Mostly done and mostly good enough.  Individual starter package problems should now be reported as separate issues.
