### ISSUE TITLE
store raw bot input/output for debugging?

### ISSUE THREAD

**Issue by McLeopold** [aichallenge/aichallenge#142]
As an aid to the contestants, store bot input/output and make available as a zip file.  Right now they can only see the replay format, which would need to be processed into bot input/output.  This would increase storage and bandwidth needs of the server.  If not implemented, someone needs to write a replay to stream converter.

Thoughts?

**Comment by Janzert** [comment]
I would be mildly opposed to storing a game in two different formats. A tools to convert the existing replay format and run a bot through the game seems much better.

**Comment by McLeopold** [comment]
This would be 2 files per bot, not exactly a replay, but still derivable from the actual replay.  (Whoops, wrong button)

**Comment by amstan** [comment]
I agree with janzert. A tool to convert the replay files to stdin and stdout would be best.
We're already at 700MB/12000 games.

**Comment by McLeopold** [comment]
We all agree not to do this in favor of a converter.
