### ISSUE TITLE
Update map generator.

### ISSUE THREAD

**Issue by McLeopold** [aichallenge/aichallenge#149]
The current map generator only has one symmetry.  It also can create maps that block easily.  Toss in a few more map types.

**Comment by smiley1983** [comment]
update - in-development source here:
https://github.com/smiley1983/rotsym_mapgen

I've written some rotational symmetry and tiling code, which could be used to create maps for 4 or 8 players. It's in OCaml. If this is useful, let me know here or on IRC and I can clean it up so it can be used by others.
Alternatively, if someone wants to write an equivalent in Python and would like something to work from, here is the source (minus actual map creation):
http://pastebin.com/9D6BYvy0 
Here is the logic; if it is flawed please let me know:
Create a sub-map which will serve as the tiling/rotating unit, named A.
Create three clockwise rotations of the sub-map in increments of 90 degrees, named B, C and D.
Tile them onto a larger map as follows:
AB
DC
The point is that the tiling is going around clockwise, like the rotation.
For the 8-player version, simply double the map:
ABAB
DCDC
You can see a simple example of a 4-player and 8-player map here (no ants marked):
http://pastebin.com/JiibpswN
edit:
It's now generating symmetric mazes, example here:
http://pastebin.com/4waYMJVY
More map types will be added over time.
One more thing: the food generation fails for the 8-player versions of these maps, even with 'random', so it has to be set to 'none' for this map:
http://pastebin.com/eVAtMjP1

**Comment by McLeopold** [comment]
I hope to add map generator piece to the manager.  Different map generators could be registered and it would create a new set of about 20 maps each day from a random generator (or use rotation).  Each generator should have a list of variables with a range that can be changed, all integers.  This way, regardless of the generator type, we can tweek the settings for each set of generated maps to provide a set that is fairly consistent in it's characteristics.  The manager will take care of making sure a new set's variables are different enough from the last time the generator was used.

**Comment by smiley1983** [comment]
After some thought and experimentation, I've determined that it will probably be necessary to manually filter any 90-degree rotation symmetric maps because of the unfortunate shapes which keep cropping up. I've trimmed the code on github a little (though it's still all there in the history) so now it's just a demonstration of the rotation logic.

The need for manual filtering may mean that this sort of symmetry is simply not a good idea, or can only be included sparingly.

**Comment by McLeopold** [comment]
Can you ant paste some examples of bad maps and why they are bad?  http://ants.zeroviz.us/

**Comment by smiley1983** [comment]
Um... I'd rather not paste them - they're bad because they resemble swastikas.

**Comment by McLeopold** [comment]
Yikes.  I was hoping for some more technical or statistical reason.  I'm still going to try 4 player rotational with my cell maze maps.  Hopefully I won't have the same problem.  I wonder how the identicon people avoid then...

It's too bad the swastika is representative of evil. :(

**Comment by mleise** [comment]
http://en.wikipedia.org/wiki/Swastika
