### ISSUE TITLE
Symmetric food is best, but limited.

### ISSUE THREAD

**Issue by McLeopold** [aichallenge/aichallenge#150]
Symmetric food only works with the symmetric map types.  If we have different types of symmetry, it will break.  It will also break if we have more than one starting ant per player.  This should be improved.

**Comment by amstan** [comment]
@antimatroid's map generator/food algorithm shouldn't be called symmetric. It's a very limited example of symmetry. It's the same as using `shape` to name a `circle`.
I would like to see ants/mapgen/SymmetricMapgen.java used as well

**Comment by McLeopold** [comment]
We will be adding symmetric info the the maps so they can define the type of symmetry they are.  It will look like this:

```
s row col [nesw][nesw]
```

Each symmetry line should refer to a starting ant.  All starting ants should have a symmetry line.  Each line needs only 1 of 'n', 's' and only 1 of 'e', 'w', which can be in either order.  There are eight total orientations, nw, ne, sw, se, wn, en, ws, es.

For an ant, if a food is spawned 3 north and 5 east, then that starting ant's square's orientation is compared to the others and spawned in a relative similar distance.  For instance, If the first ant has some food spawned and has the orientation of 'nw':

```
s x y nw .*.
         .a.
         ..*
```

Then the other orientations will spawn like this:

```
s x y ne .*.
         .a.
         *..

s x y sw ..*
         .a.
         .*.

s x y se *..
         .a.
         .*.

s x y wn ...
         *a.
         ..*

s x y en ...
         .a*
         *..

s x y ws ..*
         *a.
         ...

s x y es *..
         .a*
         ...
```

**Comment by McLeopold** [comment]
Symmetry is now auto-detected, as of like 3 months ago.
