### ISSUE TITLE
allow for selecting active version, or no version

### ISSUE THREAD

**Issue by McLeopold** [aichallenge/aichallenge#152]
Give some control to the players over their current submission that is active.  Only 1.  Also, altruistic players can take a crappy bot out of rotation (and get to be first in line when they resubmit)

**Comment by amstan** [comment]
Isn't this done?

**Comment by McLeopold** [comment]
Janzert is against selecting old version because we don't know how it would affect ratings.  We can currently deactivate the latest submission or reactivate it.
