### ISSUE TITLE
Possible bug in engine/replay

### ISSUE THREAD

**Issue by McLeopold** [aichallenge/aichallenge#159]
http://aichallengebeta.hypertriangle.com/visualizer.php?game=12534&turn=589&row=1&col=42
2 ants die in turn 590, but look like the incorrect ones
2 ants die in turn 591, but are not near the enemy

**Comment by n-ham** [comment]
Looks to me like the ants are colliding.

**Comment by zaphus** [comment]
Maybe it would help if the visualizer could show a different animation for colliding deaths, or even just draw an X through any location with more than one ant in it, so that when playing back you can spot them

**Comment by McLeopold** [comment]
There are still line in the replay that indicate ants were within fighting range for the first fight.  Whatever the bug is, the visualizer is showing incorrect information as well.

**Comment by McLeopold** [comment]
Okay, in the replay, the lines indicated battle are correct.

For the first, the two ants that survived only received 1/2 damage, but the one ant that died received 2 damage.  The other 2 ants that died are a result of collisions and it is only coincidence that they appear in the same formation.

The second turn is the same, a separate battle above that is correct, and 2 locations down below that collided.

So there is no bug.
