### ISSUE TITLE
Write replay converter.

### ISSUE THREAD

**Issue by McLeopold** [aichallenge/aichallenge#160]
Preferable it will produce the same output as the engine produces when logging the stream format and the bot io.  Replay files can contain stderr if run locally, but will not when run on the official server.

**Comment by zaphus** [comment]
I second this.  I want to be able to take data from a replay (on the server) and feed it to my bot.  Just from a single frame although it might be interesting to get an entire games worth of data.
This will be especially useful for finding out why a bot crashes or why it times out

**Comment by McLeopold** [comment]
Right now for local games you can capture bot input.  You can then send it back through using redirection if you want to do breakpoints or anything like that.
