### ISSUE TITLE
Iak artwork

### ISSUE THREAD

**Issue by amstan** [aichallenge/aichallenge#162]
I got in touch with a graphics designer (geartrooper) who could cooperate with us in adding artwork through the site and to promotional materials(i'm thinking youtube and posters).

Examples of his ants artwork can be found at http://home.hypertriangle.com/~alex/aichallenge/ants/iak-artwork/. I tried integrating Iak on the [homepage](http://home.hypertriangle.com/~alex/aichallenge/website), seems to look good.

I wouldn't mind seeing that little guy around on a few pages. What do you guys think?

**Comment by Janzert** [comment]
I'm not at all a graphics designer so am rather the last one that should be asked about this; to me though the feel of this doesn't seem to fit with the rest of the design. But I don't really have a strong feel against it either.

**Comment by aarossig** [comment]
I agree with Janzert. I like the artwork and the illustrations are nice. I just don't think that they fit in with our design.

**Comment by McLeopold** [comment]
I like it.  Our design right now is html+css only, which is colors and borders.  There is one graphic that could be switched out and one favicon that should be replaced anyway.

The weird dinosaur that is supposed to be a horse doesn't fit.

**Comment by mleise** [comment]
There is no such thing as male soldier ants and tiny dinosaurs, but illustrations could really make some pages more enjoyable to read. An armed ant could look good on the battle resolution topic for example.
