### ISSUE TITLE
Scala - fails to start

### ISSUE THREAD

**Issue by Synesso** [aichallenge/aichallenge#163]
Scala starter pack, when deployed, reports:

```
Function Test failure: Failed to start ['?']
```

I assume this means the worker did not wait long enough for the Scala runtime?

**Comment by Synesso** [comment]
I suspect https://github.com/aichallenge/aichallenge/blob/epsilon/worker/compiler.py#L360 should read 

```
"scala MyBot",
```

**Comment by Janzert** [comment]
Not sure why you closed the issue already, but I have now added a scala start command to the language definition.

**Comment by Synesso** [comment]
Thanks. I closed the issue because I had built a patch. Then I realised my
patch was bad and I spent a few hours in github newbie hell before I ran out
of time. Thanks for the fix. I'll try it out.
