### ISSUE TITLE
game 16756 - that isn't my bot ... are you mixing bots up?

### ISSUE THREAD

**Issue by mynameisgeorge** [aichallenge/aichallenge#167]
hi, i am 99% sure that the bot 'george' in game 16756 is not mine  (i have played the map on my machine, though it seems with different seed, and it does not play like that, ever).
i have seen this in 1 or 2 other cases, previously (also in the early days of the previous contest).

if someone could take a look, or maybe be on the lookout for other people reporting the same thing, that would be great.

i'm looking forward to the contest proper, cheers,
george

**Comment by mynameisgeorge** [comment]
ok, i added the:
std::cerr << "bot: george" << std::endl;
and  
std::cerr << "bot: george    turn: " << turn_number << std::endl;
to my bot.   

Could you check games  #17608  and  #17180   to see what the standard error output is?
thanks.

**Comment by mynameisgeorge** [comment]
error, didnt mean to close.  apologies.

**Comment by McLeopold** [comment]
Both games show your bot with your user_id and your submission_id with the correct game_rank matching to the replay.  So there is no mixup.

game 17608: 

+---------+---------------+-----------+-----------+------------------+
| user_id | submission_id | game_rank | player_id | left(errors, 11) |
+---------+---------------+-----------+-----------+------------------+
|      11 |           194 |         0 |         5 |                  |
|      60 |           240 |         8 |         6 | turn    0 b      |
|      67 |           266 |         2 |         3 |                  |
|      25 |           322 |         5 |         8 | turn  254 b      |
|      77 |           381 |         4 |         4 |                  |
|      81 |           383 |         3 |         2 | turn   99 b      |
|      68 |           424 |         8 |         0 | turn    0 b      |
|     100 |           442 |         6 |         1 |                  |
|      22 |           465 |         1 |         9 |                  |
|      38 |           487 |         7 |         7 | bot: george      |
+---------+---------------+-----------+-----------+------------------+

game 17180:

+---------+---------------+-----------+-----------+------------------+
| user_id | submission_id | game_rank | player_id | left(errors, 11) |
+---------+---------------+-----------+-----------+------------------+
|       7 |             7 |         5 |         1 |                  |
|      11 |           194 |         3 |         3 |                  |
|      27 |           434 |         2 |         4 | turn   18 b      |
|      35 |           316 |         1 |         5 | turn   26 b      |
|      38 |           487 |         4 |         6 | bot: george      |
|      78 |           484 |         0 |         2 |                  |
|      86 |           410 |         5 |         0 |                  |
+---------+---------------+-----------+-----------+------------------+
