### ISSUE TITLE
Website issues/improvements

### ISSUE THREAD

**Issue by zaphus** [aichallenge/aichallenge#168]
A list of issues and improvements I'd suggest for the website:
All seen under IE9

Issues:
- Under 'Recent Submissions' the "more" button takes you to a blank page without your name on it and no submissions shown
- On the My Profile page the right hand table of shortcuts (the green section) are not available, so uploading code cannot be done from My Profile
- On the My Profile page, Current Rank is no longer working (it has previously worked)

Suggestions:
- On My Profile, next to "Next Game should be played soon" include a "This page refreshed at XX:XX"  so you have some concept of how long it has been since your last game
- Replay viewer:  It can take some time to figure out which colour your ants are each time you view a game.  Something that lets me see my bots more clearly (e.g. lets me use green for my bots, the others get a greys or something) would help a lot.  The fog of war helps but can make it hard to watch.

**Comment by McLeopold** [comment]
Can you split each of these into their own issue?

**Comment by zaphus** [comment]
All split out into separate issues.  closing this one
