### ISSUE TITLE
Replay viewer - cannot select fog of war for bots 9 & 10

### ISSUE THREAD

**Issue by zaphus** [aichallenge/aichallenge#169]
The replay viewer has icons down the right hand side to select fog of war viewing, however it only shows the clear option, plus 7 more icons, plus a bit of the 8th icon.  There are no icons for bots 9 and 10.

Reduce the size of the icons so that 11 icons fit into the space provided (assuming 10 is the max number of bots allowed)

**Comment by McLeopold** [comment]
I agree, I have to maximize the viewer to use these buttons.  It would be nice if the buttons looked consistent as well.  The lower section has a different theme than the right section.
