### ISSUE TITLE
Secure password storage

### ISSUE THREAD

**Issue by amstan** [aichallenge/aichallenge#17]
I was shunned last year from #mysql because I told them we don't hash passwords.

We should get better password systems:
- _Bad_: unhashed, stored plain text
- _Good_: simple hashed with md5 or sha1 << Epsilon does this currently
- _Better_: md5/sha1+per user salt << Zeta: Django does this by default
- _Best_: crypt with a high workload + salt. md5/sha1 was designed so it's fast as possible. We don't want fast, we want as slow as possible so passwords take forever to crack. crypt allows adjusting how slow the hashing gets.

For epsilon, we might want to look at what phpBB is doing. They have some custom password functions.

**Comment by jeremyroman** [comment]
Wait, WHAT? Salted hashes are the correct way to go. And don't worry about your "Best" option, because fast is fine for hashes. It's not practical to make rainbow tables for salted hashes, only for relatively short passwords.

**Comment by stephen-smith** [comment]
Agreed, salted MD5 is still safe even though MD5 has a number of attacks and salted SHA-1 is still safe even though SHA-1 is showing its age.  The solution labeled "Better" is actually the best, until SHA-3 is released or we are forced to move to SHA-2 because SHA-1 is broken.

I think is issue is closable.

**Comment by McLeopold** [comment]
For epsilon, we are using the php crypt function with random salt using sha2 and enough rounds to use about 50ms which is all stored in the database as one string.
