### ISSUE TITLE
Website: Game history shows skill as 0.00 for many games

### ISSUE THREAD

**Issue by zaphus** [aichallenge/aichallenge#170]
Approximately 1 in 3 games is currently showing a skill of 0.00 on the game history in the player profile page

Taken from bot 'Zaphus'

Version 15 
8 Jun 8:49 0.00 
8 Jun 8:38 0.00 
8 Jun 8:23 55.05
8 Jun 8:16 55.45
8 Jun 8:04 0.00 
8 Jun 7:49 56.36
8 Jun 6:51 55.88
8 Jun 6:36 0.00 

The bot did well in these matches, e.g. the first in that list:
8 Jun 8:49 0.00 (1)Zaphus (2)davidjliu (3)hbhasker2 (4)AntStar (5)heikoh (6)sids.aquarius (7)drenus_  

From the webpage it is hard to tell if the skill really is being computed incorrectly as 0, or displayed wrong, or some other issue.

**Comment by Janzert** [comment]
This is just another symptom of the beta server having problems running java at times. The updater is not able to start so the skill doesn't get updated or added to the game information. I have been periodically rerunning against the games missing the updates and have now created a script that can be easily run to do it.
