### ISSUE TITLE
Under 'Recent Submissions' the "more" button takes you to a blank page

### ISSUE THREAD

**Issue by zaphus** [aichallenge/aichallenge#172]
(Tested with IE9)

Under 'Recent Submissions' the "more" button takes you to a blank page without your name on it and no submissions shown

**Comment by aerique** [comment]
This works for me on FF5 and Chrome.  Has this been fixed or is this solely an IE9 issue?

**Comment by McLeopold** [comment]
I have made changes to some web pages, so let's call this fixed and open a new issue if something goes wrong.
