### ISSUE TITLE
On the My Profile page, No ranking available for bots with high-water entries

### ISSUE THREAD

**Issue by zaphus** [aichallenge/aichallenge#174]
On the My Profile page, Current Rank is no longer working (it has previously worked) for the bot Zaphus

It is working for other bots (I didnt check all, but the ones I checked were good)
This may be because I currently have a ghost at the top of the leaderboard, above position 1

Edit:  Confirmed, those bots with high water entries all receive "Current Rank: N/A. No ranking available" despite having a position on the ladder (below their high water)

**Comment by McLeopold** [comment]
ghosts are gone, rankings table not used
