### ISSUE TITLE
Replay viewer: Improvements to help you see your bot

### ISSUE THREAD

**Issue by zaphus** [aichallenge/aichallenge#176]
Replay viewer: It can take some time to figure out which colour your ants are each time you view a game. 

Something that lets me see my bots more clearly (e.g. lets me use green for my bots, the others get a greys or something) would help a lot. 
The fog of war helps but can make it hard to watch and runs slower, and it still takes a while to figure out which of those are you.

**Comment by mleise** [comment]
Maybe a GET parameter could be added that identifies the 'primary' user when selecting a game from this users profile. That user would switch colors with the first player (red) in the game. Would that be a solution for you?
This would mean a little change to the profile page php and the visualizer, so it is likely to be done.

**Comment by zaphus** [comment]
Yes, that does sound like a good compromise.

**Comment by mleise** [comment]
Don't close it yet. It has to be done first! :-)
I have added support for the GET parameter 'user' in the visualizer. I look for the value of this variable in the 'user_ids' field of the replay meta data and set the color to (currently) red for this player. I'll assign this to whoever worked most on the php files in question now.

**Comment by zaphus** [comment]
I didnt mean to close it, I thought I just clicked on comment, but the buttons are close to each other :-)

**Comment by McLeopold** [comment]
It's in there now.
