### ISSUE TITLE
Suggestion:  Allow bots to "tweet" a short char string into the replay for debugging on live servers

### ISSUE THREAD

**Issue by zaphus** [aichallenge/aichallenge#177]
On each turn, allow the bot to add
    t string
to their move (once per turn, limited to say 12 characters)

In the replay, add a button/box to show the tweet for that turn from an individual bot. (truncated to a reasonable number of characters).  

this can be used to help people figure out what actually happened by adding simple debug info
e.g.
t 102 44 kill!

Downside:
people could put:
    t motherfarnarkler
or something more offensive
plus if you use really obvious tweets then you'd give away some tactics, but that is your own fault...

**Comment by McLeopold** [comment]
You can already output to stderr and we will capture it.  You only get 1024 chars, the first and last 512.  And only you can see it, eventually.

**Comment by zaphus** [comment]
Ah, ok - didn't realise that.   1024 chars is pretty small for a 2000 turn game, enough for 5 chars every 20 turns (including putting in the turn number) - but it's way better than nothing
e.g.

23: feed
999: hunt
1234:killm
