### ISSUE TITLE
Games history page: Allow sorting by Map & Position

### ISSUE THREAD

**Issue by zaphus** [aichallenge/aichallenge#178]
It would be very helpful to be able to sort your games history by:
Date (current behaviour)
Map (so you can see how you do on different maps)
Position (so you can find the matches you do best/worst in)

You would still group by submission number, but sort within that submission.

**Comment by McLeopold** [comment]
I'd like this to be done with the jQuery Tablesorter 2.0 plugin.  I used in planetwars on my tcp server.

**Comment by McLeopold** [comment]
Done.
