### ISSUE TITLE
removing food information after a spawn [c++ starter bot]

### ISSUE THREAD

**Issue by carlopi** [aichallenge/aichallenge#181]
Seem that there is a problem in State.cc, cause when a new ant is spawn in a certain location, food[location] remain set to 1.
A possible solution is add "state.grid[row][col].isFood = 0;" after these line:
else if(inputType == "a") //live ant square
            {
                is >> row >> col >> player;
                state.grid[row][col].ant = player;
  state.grid[row][col].isFood = 0; <------------------- insert this row

ps: george1914 posed this question on #aichallenge 10 june

**Comment by mynameisgeorge** [comment]
i think that more is also needed - food that was seen, but then spawned when out of sight, needs to be removed also (when its square becomes visible again).   so some more code needs adding i think - e.g. check every visible square, and if the input did not say we had food, then set food to zero?

**Comment by carlopi** [comment]
So maybe a solution can be:
-at the beginning of the turn push the food location on a vector V
-when looking for visibility set food[]=0 for all visible location
-set every location on the vector V to food[]=1

**Comment by zaphus** [comment]
I'm pretty sure this was already done during the last few days - the C++ starter bot has been updated , if you look at the latest version of square.h you'll see it resets isFood for every square that gets reset (which is all of them)

**Comment by n-ham** [comment]
I updated this a couple of days ago guys, sorry for being so slack. The beta site still doesn't have the updated version, so you will need to download it from github directly if you want the new version.

Also, the timer has been fixed so that it should work for windows compilers now too.
