### ISSUE TITLE
Final placings are not properly calculated in the replay/visualiser

### ISSUE THREAD

**Issue by zaphus** [aichallenge/aichallenge#184]
This game (below) shows an example of the final placings not being correctly represented in the replay
The winner is the highest score, Including the bonus

http://aichallengebeta.hypertriangle.com/visualizer.php?game=20074

The highest score is Zaphus_Blocktest (because Zaphus timed out, giving the bonus to Blocktest)
The replay shows
1st Zaphus
2nd Zaphus_Blocktest

scores were:
Zaphus: 4070
Zaphus_Blocktest:  937+5252 = 6189

This means the Blocktest version should have won the match.

The game history shows the correct order (Zaphus_Blocktest as the winner), hopefully rankings are calculated from that

(Edit: Updated title to be a better description of the problem)

**Comment by mleise** [comment]
thanks for the report, zaphus. This was simply a display issue in the visualizer which is completely independent from the rank calculation on the web site.
