### ISSUE TITLE
Overview of bot error since last submission

### ISSUE THREAD

**Issue by aerique** [aichallenge/aichallenge#187]
It would be nice to have a page where all the errors since the bot's last update are displayed.  This saves having through each and every game to see whether one's bot has any errors.

**Comment by McLeopold** [comment]
At some point the game list table for a submission will be sortable.  At that point you should be able to sort by result (survived, eliminated, timeout, crashed, invalid) so you can put all the crashes at the top.  Then looking at individual pages won't be so bad.

**Comment by McLeopold** [comment]
This has been done.  I might still create a query of last bot error or something.
