### ISSUE TITLE
Need a stable trueskill implementation

### ISSUE THREAD

**Issue by Janzert** [aichallenge/aichallenge#191]
The current trueskill implementation (JSkills) occasionally crashes on the results of games. Previously a python implementation was tried that was giving incorrect results. We need a completely stable and accurate implementation.

**Comment by amstan** [comment]
I'm offering to send a bugreport to the original python library. Can someone give me a test case where the python one and the microsoft one disagrees?

**Comment by McLeopold** [comment]
We've switched to the moserware/PHPSkills project.  This also has the benefit of streamlining the calculations into the api_game_result page so the database isn't in a state of flux for a second.
