### ISSUE TITLE
End the game early

### ISSUE THREAD

**Issue by McLeopold** [aichallenge/aichallenge#193]
Possible metrics to end are:
- 1 bot controls 95% or greater territory for 100 turns
- Only 1 bot has spawned new ants in the last 100 turns
- 1 bot has 10 times more ants than all other opponents combined

If ended early, the bonus is split evenly.  This means bots with more ants and more territory will get less bonus than if they had ended the game earlier.  Bots with less ants and less territory have an incentive to survive longer.

**Comment by Janzert** [comment]
My favored metric at the moment is a population based one (e.g. the last example above). Probably of the form 1 player has X% of the total living ants for Y consecutive turns. With X and Y being somewhere around 95% and 100 to 150 turns.

**Comment by McLeopold** [comment]
I'm liking the results.  This is done.
