### ISSUE TITLE
Add a "last 50 games on server" page

### ISSUE THREAD

**Issue by zaphus** [aichallenge/aichallenge#199]
Add a page that lists the last 50 (or other arbitrary number) matches played on the server.  
Display it like the "My Profile" page except there should be no ranking (since no one bot is the focus)

This lets people go and look at recent games for inspiration, but also helps us detect if the scheduler/matchmaker has broken.

**Comment by olexs** [comment]
The page is there now: http://antsbeta.janzert.com/games.php, but not linked anywhere.

**Comment by Janzert** [comment]
game list has been added and linked in sidebar
