### ISSUE TITLE
Some country codes not displaying correctly

### ISSUE THREAD

**Issue by zaphus** [aichallenge/aichallenge#200]
Check out Mr Blobby, he's from
                       Saint Barth&Atilde;�&Acirc;&copy;lemy

http://aichallengebeta.hypertriangle.com/profile.php?user=225

There are other countries that display badly, you can see them from the country picker.   If it were your country you'd care

**Comment by aerique** [comment]
Fixed by http://github.com/aichallenge/aichallenge/commit/815f7540624b7bb561a789514f90f45dbb2e8f38
