### ISSUE TITLE
symmetric food spawning unfair on symmetric lines

### ISSUE THREAD

**Issue by McLeopold** [aichallenge/aichallenge#206]
I'm considering not letting food spawn next to another food.  This is relevant when a map has some type of mirror symmetry.  This creates a dead zone of land that doesn't spawn.  We've always wanted the amount of land controlled to be roughly linked to the amount of food spawned per turn.  This would make the ratios off, bots would not be able to calculate exactly their percentage of "live" land they control, unless they could detect the symmetric lines.

Having a dead zone may be offset by the fact that food will still spawn close to the line at the same time.  If you hold the symmetric line, you will have a lower percentage of food spawned in your area, but a higher percentage that you will get all of the symmetric set.

We could also just spawn 1 food, but then we'd have to choose which side of the line to spawn on.

This problem becomes worse with mirror symmetry across 2 lines, because 4 food may spawn next to each other.

I'm looking for ideas for fixes.  I'd rather not give up mirror symmetry.

**Comment by sir-macelon** [comment]
Examples:
http://aichallengebeta.hypertriangle.com/visualizer.php?game=52727&turn=42&row=61&col=36
http://aichallengebeta.hypertriangle.com/visualizer.php?game=52240
http://aichallengebeta.hypertriangle.com/visualizer.php?game=54058&turn=75&row=0&col=0
http://aichallengebeta.hypertriangle.com/visualizer.php?game=52918&turn=60&row=22&col=24

**Comment by carlopi** [comment]
For 2 near cell (eg. mirror symmetry along the mirror axis) I think that spawning only 1 food for cell in the same symmetry group of tile but near than 2 (or maybe 1.5) can be a good solution. This partialy broke symmetry, but i think small assymmetry is better that "dead land" or "randomly boost one side".

Another possibility is weight the map generator to geneate less mirror map, and more glide reflection (http://ants.zeroviz.us/85ef6/) or composition of tessellation, 180° symmetry, 90° symmetry and glide.

For 4 near cell (eg. 2 mirror axis that meet in one point, or a 90° center of symmetry) the best solution can be fill all this zone with water. Say that each tile that have the second nearest tile on his symmetry group near than 3 (or more) should be water. (there can be only few point in the map with this proprety, so it's not a problem. for mirror symmetry is not possible to block the entire axis, this cause un-connected map)

**Comment by McLeopold** [comment]
I think the deadzones are in.  Anyway, the game spec is going to stay and not be changed at this point.
