### ISSUE TITLE
C# Starter Bot fails the test case

### ISSUE THREAD

**Issue by amstan** [aichallenge/aichallenge#207]
The starter bot made by @coastwise doesn't seem to pass the test case anymore.
It seems like it used to: http://aichallengebeta.hypertriangle.com/profile.php?user=184

**Comment by VilleH** [comment]
What is version number of Mono on the server? Would it be possible to update it to latest one? At least on environment page it says that the version is 1.2.6 and current version is 2.10.2.

**Comment by amstan** [comment]
```
alex@aichallengebeta:~$ mono -V
Mono JIT compiler version 2.6.7 (Debian 2.6.7-5ubuntu3)
Copyright (C) 2002-2010 Novell, Inc and Contributors. www.mono-project.com
        TLS:           __thread
        GC:            Included Boehm (with typed GC and Parallel Mark)
        SIGSEGV:       altstack
        Notifications: epoll                                                                                                                                                                                                                
        Architecture:  amd64                                                                                                                                                                                                                
        Disabled:      none
```

Please see the Versions heading from: https://github.com/aichallenge/aichallenge/issues/3

**Comment by VilleH** [comment]
Seems that C# bot timeouts now constantly, I presume that it worked when it was uploaded first time:
http://aichallengebeta.hypertriangle.com/visualizer.php?game=62120

**Comment by VilleH** [comment]
I did a bit of detective work and found out that csharp_starter and cs_testbot both stopped working (started timeouting) between "2 Jul 15:03" and "2 Jul 17:22" when the server was down. Seems more like a server issue as there aren't any commits done at that time.

csharp_starter games: http://aichallengebeta.hypertriangle.com/profile_games.php?user=184&page=6
cs_testbot games: http://aichallengebeta.hypertriangle.com/profile_games.php?user=87&page=5

cs_testbot last working game: http://aichallengebeta.hypertriangle.com/visualizer.php?game=53577
and first timeout: http://aichallengebeta.hypertriangle.com/visualizer.php?game=53642&user=87

**Comment by KasperHoldum** [comment]
I didn't find any changes that should break the C# bots in the compiling- or testing sections of the project. Could this be a server issue?

There was a commit in before the server restart with the following line change: 'sed -i 's/dist[/]//g' tools/util/block_test.cmd tools/util/block_test.sh tools/play_one_game.cmd tools/play_one_game.sh'. Any chance this could have caused issues?

**Comment by amstan** [comment]
I compiled and ./test_bot.sh 'ed the starter bot manually:

```
alex@aichallengebeta:~/csharp$ gmcs -warn:0 -out:MyBot.exe *.cs
alex@aichallengebeta:~/csharp$ ls
Ants.cs  Bot.cs  csharp_starter_package.zip  GameState.cs  Location.cs  MyBot.cs  MyBot.exe  Tile.cs

contest@aichallengebeta:~/aichallenge/ants$ ./test_bot.sh ~alex/csharp/MyBot.exe 
running for 30 turns
                ant_count food cutoff c_turns winning w_turn ranking_bots r_turn score 
turn    0 stats:  [3, 1, 0]  23    -       0     None     0        None       0    [3, 1]
turn    1 bot 0 ignored actions:
o 3 18 w # move blocked
turn    1 stats:  [4, 1, 0]  22    -       0      [0]     1       [0, 1]      1    [4, 1]
turn    2 stats:  [4, 2, 0]  21    -       0      [0]     1       [0, 1]      1    [4, 2]
turn    3 stats:  [4, 3, 0]  20    -       0      [0]     1       [0, 1]      1    [4, 3]
turn    4 stats:  [4, 5, 0]  18    -       0      [1]     4       [1, 0]      4    [4, 5]
turn    5 stats:  [4, 6, 0]  17    -       0      [1]     4       [1, 0]      4    [4, 6]
turn    6 stats:  [4, 7, 0]  16    -       0      [1]     4       [1, 0]      4    [4, 7]
turn    7 stats:  [4, 8, 0]  15    -       0      [1]     4       [1, 0]      4    [4, 8]
turn    8 stats:  [5, 9, 0]  13    -       0      [1]     4       [1, 0]      4    [5, 9]
turn    9 stats:  [5, 9, 0]  13    -       0      [1]     4       [1, 0]      4    [5, 9]
turn   10 stats:  [5, 9, 0]  13    -       0      [1]     4       [1, 0]      4    [5, 9]
turn   11 stats:  [5, 10, 0]  12    -       0      [1]     4       [1, 0]      4    [5, 10]
turn   12 stats:  [5, 11, 0]  11    -       0      [1]     4       [1, 0]      4    [5, 11]
turn   13 stats:  [5, 13, 0]  9     -       0      [1]     4       [1, 0]      4    [5, 13]
turn   14 stats:  [5, 13, 0]  9     -       0      [1]     4       [1, 0]      4    [5, 13]
turn   15 stats:  [5, 13, 0]  9     -       0      [1]     4       [1, 0]      4    [5, 13]
turn   16 stats:  [5, 13, 0]  9     -       0      [1]     4       [1, 0]      4    [5, 13]
turn   17 stats:  [3, 11, 0]  9     -       0      [1]     4       [1, 0]      4    [9, 17]
turn   18 stats:  [1, 9, 0]  9     -       0      [1]     4       [1, 0]      4    [13, 21]
turn   19 stats:  [1, 9, 0]  9     -       0      [1]     4       [1, 0]      4    [13, 21]
turn   20 stats:  [1, 9, 0]  9     -       0      [1]     4       [1, 0]      4    [13, 21]
turn   21 stats:  [1, 9, 0]  9     -       0      [1]     4       [1, 0]      4    [13, 21]
turn   22 bot 0 eliminated
waiting 0.25 seconds for bots to process end turn
turn   22 stats:  [0, 8, 0]  9     -       0      [1]     4       [1, 0]      4    [15, 23]
score 15 91
status eliminated survived
waiting 0.25 seconds for bots to process end turn
```

**Comment by KasperHoldum** [comment]
The test manually done in the above answer was done on the main server, which isn't the actual server that runs the test at the moment. Could someone with access to the worker servers run the above test inside a sandbox'ed worker?

**Comment by KasperHoldum** [comment]
C# is working again as per yesterday evening. I don't know if anyone actively fixed anything, but both compilation, testing and actual playing works.

**Comment by Garion** [comment]
It seems the problem is back, all C# bots have timeouts at their first turn. Was there any change made recently?

**Comment by KasperHoldum** [comment]
I'm quite sure there was a server restart yesterday or early this morning. The problem seems to appear every time there is a server restart?

**Comment by Janzert** [comment]
Not sure why it effect C# but after a change to the way the sandbox filesystems are handled they seem to be working fine now.
