### ISSUE TITLE
duplicated games and games with no rating calculations.

### ISSUE THREAD

**Issue by ashokae** [aichallenge/aichallenge#210]
A friend of mine has 2 games listed in his profile page which are identical and played on the same time. looks like the server has duplicated that game. This will affect the accuracy of ratings for all players concerned.  games 65833 and 65834.

Also, ratings havn't been calculated for these 2 games and they are displayed as 0.0

In the 2 games played by my friends immediately after these two games, again ratings havn't been calculated those 2 games are 65836 and 65838

all in all, my friend has 4 straight games without rating calculations. Don't know duplication of first 2 games are in any way related to missed ratings or not but 4 missed our ratings mean his current rating is significantly inaccurate.

There was a server slowdown in the time period immediately after those games, so might have caused by a unresponsive server component ?

**Comment by McLeopold** [comment]
In the second case, this was caused by the poor matchmaking algo at the time.  Each replay file has a different matchup number.  The algo has since been fixed.  This is not a case of 2 workers grabbing the same matchup data.
