### ISSUE TITLE
test_bot.sh and play_one_game.sh are missing in tools.zip

### ISSUE THREAD

**Issue by SSNikolaevich** [aichallenge/aichallenge#212]
In tools.zip, which I resently download missing test_bot.sh and play_one_game.sh files. Only *.cmd presents.

**Comment by mleise** [comment]
Sorry for the inconvenience, please download http://aichallengebeta.hypertriangle.com/tools.tar.bz2
It has the .sh files instead of the .cmd files with executable bit set. If any links should be updated please reopen this issue.

**Comment by jennifersmith** [comment]
Hi,

The link here just points to the zipped version of the tools:

http://aichallengebeta.hypertriangle.com/using_the_tools.php

Thanks

Jen

**Comment by mleise** [comment]
Am 05.08.2011, 14:37 Uhr, schrieb jennifersmith  
reply@reply.github.com:

> Hi,
> 
> The link here just points to the zipped version of the tools:
> 
> http://aichallengebeta.hypertriangle.com/using_the_tools.php
> 
> Thanks
> 
> Jen

I updated the Wiki (on Github) a while ago, but I didn't know how to  
update the beta server version. I expected someone else to make some  
changes to the Wiki in the meantime and do this. So, shame on me.

Marco
