### ISSUE TITLE
Bad battle result?

### ISSUE THREAD

**Issue by TTrumpeTT** [aichallenge/aichallenge#213]
http://aichallengebeta.hypertriangle.com/visualizer.php?game=67775&user=226 move 185
Why two of red's died?
Purple ant(25,21) attacked 3 of red's ants. So there is no >=1 power to kill any red ant.

**Comment by jmcarthur** [comment]
I believe this outcome is correct. Here's the situation (A is red, B is purple):

```
AA.......
.AAAAAAAA
.........
.BB......
```

The number of enemy ants within range of each ant:

```
00.......
.22100000
.........
.23......
```

The rule is that if an ant is within range of an enemy with an equal or lesser number, it dies.
- The leftmost red ant is in range of an enemy with the same number, so it dies.
- The second red and on the second row is in range of an enemy with the same number, so it dies.
- The third red ant is only in range of an enemy ants with a larger number, so it lives.
- The left purple ant is in range of two enemy ants with equal numbers, so it dies.
- The right purple ant is in range of three enemy ants with smaller numbers, so it dies.

Just in case, I won't close this issue. Somebody else can do that if they agree with me that this is correct behavior.

**Comment by McLeopold** [comment]
The engine is correct.

**Comment by TTrumpeTT** [comment]
Is this description compatibile with that http://aichallengebeta.hypertriangle.com/specification.php ? 

"If there are opponent ants within the attack radius of an ant, the ants automatically engage in a battle, even over water. The attack radius is currently set at (\small \sqrt{6}). The battles are resolved with the following steps:
1. Ants with enemies in range distribute 1 point of damage, split evenly among those enemies.
2. Ants with at least 1 full point of damage from that turn die.
   "

**Comment by jmcarthur** [comment]
The spec on the beta site is out of date. Until the actual contest begins, the best source for you to read is the specification [here on Github](https://github.com/aichallenge/aichallenge/wiki/Ants-Game-Specification). For more details on the battle resolution method itself, see the [Focus Battle Resolution Method](https://github.com/aichallenge/aichallenge/wiki/Ants-focus-battle-resolution-method). Also note that the [front page](http://aichallengebeta.hypertriangle.com/) of the beta site points out this change at the very top, under "Notice: We are testing setting changes."
