### ISSUE TITLE
Top players dont play against each other

### ISSUE THREAD

**Issue by TRavary** [aichallenge/aichallenge#215]
```
Played vs    sir_macelon    FlagCapper    TRavary    GreenTea    antimatroid    OlexandrT    Sto03RepliCrush davidjliu Zaphtest02 pachalmars
sir_macelon           50             0          0           0              0            0                 16         0         15         13
FlagCapper             0            50          0           0              0            0                 16         0         14         13
TRavary                0             0         50           0              0            0                 16         0         16         12
GreenTea               0             0          0          50              0            0                 16         0         15         14
antimatroid            0             0          0           0             50            0                 16         0         16         13
OlexandrT              0             0          0           0              0           50                 15         0         16         12
Sto03RepliCrush        6             6          5           6              5            6                 50         6          3          9
davidjliu              0             0          0           0              0            0                 13        50         16         15
Zaphtest02             5             6          5           6              6            6                  4         5         50          8
pachalmars             6             5          5           5              5            4                 10         6          8         50
```

In row the number of games played vs each other for the 10 first players during their 50 last games

It seems to be a matchmaking issue

**Comment by zaphus** [comment]
That's a pretty major issue.

**Comment by ashokae** [comment]
This prblem has worsened now. Of the current first 13 bots, 10 are no longer playing against each other! (revolt, sir_macelon, Kadiyaa, GreenTea, DarkMomo, eashoka, traveray, paratrechina, ThisIsNotaBug, Hammerock)  So the ranking among them is calculated simply using their performance against mathis, UVAnts and Trumpet. 

This problem seem worsening. Until recently DarkMomo and revolt was available for other top starving bots to play against  with but not anymore.

What if bots can freely play against each other ? That will make the match making code simpler as well. For instance, for every game for any bot, choose 33% of opponents from any bot with higher skill, 33% from any bot with more or less same skill level, 33% with any bot which are lower in skill. That way, all bots will have fair probability against playing any other bot.

**Comment by McLeopold** [comment]
Latest changes should have fixed this.

**Comment by ashokae** [comment]
great job! working beautifully now. tx.
