### ISSUE TITLE
Starter packages on site don't contain tools/visualizer

### ISSUE THREAD

**Issue by DanielVF** [aichallenge/aichallenge#216]
At least as far as I've tested (ruby, java, python) the starter pack downloads don't contain the tools/visualizer to actually play the game locally. They contain only the starting bot code and the supporting libraries for it.

**Comment by TRavary** [comment]
The tools can be download separatly here :

http://aichallengebeta.hypertriangle.com/using_the_tools.php

You can reach this page bottom the "five minutes quickstart guide" page

**Comment by DanielVF** [comment]
Wow. I can't read, apparently. Thanks.
