### ISSUE TITLE
Having problems running tools on OS X

### ISSUE THREAD

**Issue by DanielVF** [aichallenge/aichallenge#217]
I'm trying to run playgame.py:

Getting a syntax error

```
File "/Users/dvf/Downloads/tools/ants.py", line 1116
  orientations = [[(ants[0].loc, 0, {i: i for i in range(self.num_players)})]]
```

Also, ants.py uses OrderedDict, which is in python 2.7. OS X ships with 2.6.

**Comment by submitteddenied** [comment]
I resolved this by throwing the code from [here](http://code.activestate.com/recipes/576693/) into a file called `ordereddict.py` in the ants folder.

You can also try `pip install ordereddict`

Otherwise, I think the best bet is to upgrade Python :)

**Comment by McLeopold** [comment]
code looks different now, works with 2.6
