### ISSUE TITLE
combination of cutoff with no bonus and 2x kill points produces odd rankings

### ISSUE THREAD

**Issue by McLeopold** [aichallenge/aichallenge#219]
Issue raised by mcstar on irc

http://aichallengebeta.hypertriangle.com/visualizer.php?game=80781&user=17

**Comment by Janzert** [comment]
Why is there no end game bonus for cutoff games?

**Comment by sir-macelon** [comment]
I already raised a similar issue on irc: cutoff should be based on points, not on ant counts.
