### ISSUE TITLE
C++: Compilation timed out with command g++ ...

### ISSUE THREAD

**Issue by Momotebo** [aichallenge/aichallenge#226]
Hi,

I've got this error when I try to submit my c++ bot, I don't understand why because when I compile it at home with g++ it takes 10 seconds. A friend is experiencing the same trouble (also with c++)

My nickname is DarkMomoBot and my profile is here : http://aichallengebeta.hypertriangle.com/profile.php?user=385

Thanks

**Comment by TTrumpeTT** [comment]
I have the same problem.
AT LEAST what should be done immediately is: change "def compile_anything(bot_dir, timelimit=600):" to "def compile_anything(bot_dir, timelimit=6000):" (10 minutes timeout to 100 minutes).

**Comment by amstan** [comment]
@TTrumpeTT: Ummm... no? So if we have 2 workers going and there's 2 entries which take 100 minutes each, you're telling me it's acceptable to be no games for 100 minutes?

**Comment by TTrumpeTT** [comment]
On IRC you said that compilation is not running on game server, there is another server for it. Is it true?

**Comment by Janzert** [comment]
compilation is done on the workers, i.e. the same servers that games are played, not the main server. Anyway closing this since it seems nobody is having problems with it recently.
