### ISSUE TITLE
Wrong order in organization/language/country rankings

### ISSUE THREAD

**Issue by sir-macelon** [aichallenge/aichallenge#227]
Examples:
http://aichallengebeta.hypertriangle.com/organization_profile.php?org=0
http://aichallengebeta.hypertriangle.com/language_profile.php?language=Java
http://aichallengebeta.hypertriangle.com/country_profile.php?country=180

**Comment by Janzert** [comment]
The order seems to actually be correct, but the numbering is wrong. I noticed today that the numbering seems to go by descending number of games played or possibly by current submission time (which will be roughly the same).

**Comment by Janzert** [comment]
Fixed by moving the filtered rank numbering out of the sql query.
