### ISSUE TITLE
C++ starter package doesn't compile in Visual Studio 2010.

### ISSUE THREAD

**Issue by ikhramts** [aichallenge/aichallenge#228]
MSVC 2010 has the following problems with the C++ starter pack:
- In Time.h, for Windows case <time.h> should be used instead of <sys/time.h>
- In State.cc on line 54 function call to sqrt() is ambiguous (there are several versions that return different floating number types and none of which take ints).

Changes needed to fix the issue are specified here:
- https://github.com/ikhramts/aichallenge/commit/7dcdbf3e38f24aaaab2352f7f8a097e188ffe1e1
- https://github.com/ikhramts/aichallenge/commit/bad0b11d5bf187bd6a27852641fab56b35b7374e

**Comment by ikhramts** [comment]
Er, I accidentally a sentence.

First bullet point should be:
- In Time.h, for Windows case <time.h> should be included instead of <sys/time.h>.

**Comment by amstan** [comment]
You should really send a pull request if you want this fixed.
