### ISSUE TITLE
Go package float64

### ISSUE THREAD

**Issue by xarg** [aichallenge/aichallenge#231]
Since almost every function in the math package uses  float64 I would propose converting ints (for example coordinates) so that people don't need to cast every time when they want to use Fmin, Fmax, Fabs and many others.

I know that coordinates are essentially ints, but that's just not very useful if you can't use math stuff. I would really like to hear a feedback on this before starting.

**Comment by mleise** [comment]
JavaScript offers only a float64 datatype for simplictity, but I wonder why they missed min, max and abs in integer versions. I would probably write integer versions and add them to the file which holds the other general functionality. The other functions in 'math' are mostly unusable for integers anyway. Generally using float64 would make large tables of coordinates bigger than necessary (x86-64 can work well with 32-bit ints) and slower as well.
If you just want to keep it really basic though, then use float64.

**Comment by xarg** [comment]
Great. I can live with that. As long as there are Min, Max and others it should be fine. I don't know why didn't have int support in the math lib, but I guess they have reasons for doing that.
