### ISSUE TITLE
vary different game rate per player

### ISSUE THREAD

**Issue by locutus2** [aichallenge/aichallenge#235]
some bots like mine have only every 2 to 3 hours a game. Others like  jbrechtel every 10-20 minutes.
If you check the ranking its almost the submissions which have few games with have also a low game rate and therefore a high sigma.

i have looked in '2_generate_matchup.sql' file and recognized that the match_quality, which is used for player selection, depends for sigma than the mu differences. Players with low sigma would significantly selected more offen. Players with high sigma in contrast offen only selected only as seed player.

I have changed it that now as first order criteria the last game_id of a player divided by factor (currently delta=1), so players which have longer no game are preferred. For tie breaking the match_quality is used. If you want the old behaviour, delta must be set too a high number like 1000000.

Additional i fixed a sorting bug. During excluding last games opponents the 'order by' was missing, so the earlest and not the latest games are considered (see line 156 ff).

In my local test with fake data the new matchup seems good.

i make a pull request for the change.

**Comment by Janzert** [comment]
For the record I disagree that that trueskills preference for low sigma matchups is the reason why players are getting varying rates. For instance currently 5th and 6th place look like this:

Rank    Username    Country     Organization    Language    Version     Skill   Games   Rate
...
5 –   UvAntsBeta  Netherlands University of Amsterdam Java    63  89.31 ↓   86  45
6 –   paratrechina    France  Other   C   53  87.45 –   87  131

where UvAntsBeta has mu=93.85 sigma=1.51 and paratrechina has mu=91.93 sigma=1.49.

**Comment by McLeopold** [comment]
Recent changes should have fixed this issue.  The matchmaking sql was limiting potential matches to 100 submissions to prevent calculating too much.  The ordering was not correct, so the 100 selected were database order, or probably lower submission numbers.  This has been fixed.  Watch for the numbers to stabilize some.  Submissions that got cheated will still look bad because the game rate is calculated for the life of the submission.
