### ISSUE TITLE
C++: error while compiling submission - but empty error message

### ISSUE THREAD

**Issue by rbrune** [aichallenge/aichallenge#237]
I'm deepblue:
http://aichallengebeta.hypertriangle.com/profile.php?user=685

my code compiles fine without any warnings on latest Ubuntu and Mac OS X 10.6 but I get a compile error and an empty error messages when I try to submit the code to the ants beta.
I don't know what the issue is and the empty message is not really helpful :)

**Comment by mleise** [comment]
Someone familiar with the backend will have to look into why you see no error message when you are logged into your account, but for now remove the hidden MACOSX meta-data directories from your upload.

**Comment by rbrune** [comment]
Ok, did that and now I got a compile success. Not sure if that was the issue or if other changes led to it.
With PlanetWars the metadata folder certainly was not a problem.

**Comment by mleise** [comment]
Mr. Spock does not approve of your comment. It was a problem in PlanetWars, too. See http://ai-contest.com/forums/viewtopic.php?f=18&t=1157#p7700 for details. ;)

**Comment by McLeopold** [comment]
It might be the compiler puts errors on stdout.  If you can verify this is the case, then the fix will be to provide a list of output files for each step to verify that things are working.  Then we can spam you with stdout if the files are missing.

**Comment by Zannick** [comment]
The metadata folder ends up being a problem because it contains files with the same extension as code files for your bot, so the script tries to compile them, too. Perhaps for the next contest we should ignore anything in folders that start with "__" or put some warning somewhere about trying to use the native Mac zipper.
