### ISSUE TITLE
Merge epsilon-new-schema -> epsilon

### ISSUE THREAD

**Issue by amstan** [aichallenge/aichallenge#24]
I noticed that there's a few changes to epsilon-new-schema that are not actually related to the new schema, so that branch's scope is rather fuzzy.

There's a few of us that are confused in which branch to commit changes now.

None of the branches are functional either.

I propose that we merge epsilon-new-schema back into epsilon regardless how how much the new schema is done.

**Comment by Janzert** [comment]
neither branch works end to end, new-schema introduces a fair number of structural changes, all future development needs to be done in the context of those changes.

+1 for an immediate merge.

**Comment by amstan** [comment]
Done
