### ISSUE TITLE
Not appearing in rankings for my organisation or language or global

### ISSUE THREAD

**Issue by jennifersmith** [aichallenge/aichallenge#240]
Hello,

I seem to have disappeared from the global/organisation/language rankings although I have a (rather low!) ranking appearing on my profile page:

http://aichallengebeta.hypertriangle.com/profile.php?user=618

I believe the ranking is correct based on the skill points I have but I don't seem to find my name anywhere.

thanks

Jen

**Comment by jennifersmith** [comment]
Actually - could you just delete that account please?

**Comment by Janzert** [comment]
The reason the account wasn't showing up in the leaderboards was becase the script to update the leaderboards had crashed.

Probably the best way to disable an account at least for now during beta is to simply submit a broken bot that doesn't build.
