### ISSUE TITLE
The CSS is misbehaving

### ISSUE THREAD

**Issue by mleise** [aichallenge/aichallenge#241]
In Opera I have some strange CSS formatting errors that can be seen here: http://img831.imageshack.us/img831/8656/cssbug.png . This happens when I close/open the browser. Sometimes when I just switch to another tab the result is more ugly.
I also noticed that I have to explicitly set "display:table", "display:table-row" and "display:table-cell" for elements of a table that I generate in the visualizer during startup to list the configuration or errors. (Otherwise every cell is 100% wide and there is a line break after each cell.)
"font-weight:bold" and similar also have an effect for only a split second and then seem to be overridden by some CSS file loaded later. I'm not a CSS guru, so I wonder if a style attribute that I set right at the HTML node can be overridden by a CSS file? I thought that would be similar to a configuration file and command-line options with the latter overriding the config.

I've never seen Opera behave like that on any other page, so I wonder what the reason might be. Do we do anything that is considered 'experimental' or 'not the clean way'?

EDIT: It doesn't happen all the time, so I suspect sort of a race condition. Maybe different style sheets override each other there.

**Comment by McLeopold** [comment]
Your input function has the potential to load resources from the first js linked file's domain.  The google font api is a javascript file, so maybe Opera pulled in some funky font that matches the name of one of the visualizer js files?  The input function has since been fixed.  Maybe so more stress testing to see if it goes away.

P.S.

That is the most awesome error screen shot I have ever seen in my life.

**Comment by mleise** [comment]
The minified version in use on the server doesn't use the import function. It must be something else. The situation may have changed now that the page loads much faster. I'll keep an eye on it.

**Comment by mleise** [comment]
It looks like I have the same bug on other websites now and even in the email list. So even if the source was our CSS, there is clearly a serious bug in the browser.
