### ISSUE TITLE
My bot is not being tested

### ISSUE THREAD

**Issue by fabrice-decreau** [aichallenge/aichallenge#243]
I have uploaded a new version of my bot twice in the last 24 hours, and neither have been tested, although they compile fine.
http://aichallengebeta.hypertriangle.com/profile.php?user=299

It always says that there is 1 player ahead of me, it looks quite buggy.

**Comment by McLeopold** [comment]
Ouch, sorry about that.

You got stuck in the system for quite some time.  It should be back to normal now.

**Comment by fabrice-decreau** [comment]
Thanks for getting me unstuck, but it seems I got stuck again, because my bot has been tested three times in a row, and then it stopped again.

-----Message d'origine-----
De : Scott Hamilton [mailto:reply@reply.github.com] 
Envoyé : mercredi 7 septembre 2011 01:33
À : fabrice-decreau
Objet : Re: [aichallenge] My bot is not being tested (#243)

Ouch, sorry about that.

You got stuck in the system for quite some time.  It should be back to normal now.

##

**Comment by McLeopold** [comment]
This time, everyone is stopped because the workers are down.
