### ISSUE TITLE
ratings get decreased after winning a game

### ISSUE THREAD

**Issue by ashokae** [aichallenge/aichallenge#245]
2 Sep 11:03 96.89 –   1st-FlagCapper2nd-phillc    1st of 2    height_map_8    226 turns » Won at 32 »
2 Sep 4:30  96.90 –   1st-FlagCapper2nd-deepblue  1st of 2    height_map_7    90 turns » Won at 12 »

In above, FlagCapper has lost in skill level (0.01 of a point to be exact) after winning a game (with phillic) no matter how low rank the opponent is, one should not be loosing skill points after winning a game. At least that doesn't happen in ELO ratings, not sure whether this a bug in trueskill or somewhere else in the code...

**Comment by McLeopold** [comment]
Can you provide links to the 2 games?  We can look at the before and after numbers and run them through various trueskill implementations to see if there is a bug.

**Comment by ashokae** [comment]
http://aichallengebeta.hypertriangle.com/visualizer.php?game=160606&user=7

another one,

4 Sep 16:55 95.46 –   1st-revolt2nd-phillc    1st of 2    height_map_7    186 turns » Won at 39 » 
link : http://aichallengebeta.hypertriangle.com/visualizer.php?game=161667&user=407

**Comment by McLeopold** [comment]
In both of those games, the mu went up, but the uncertainty went up as well.  Both winners are very close to 100.
