### ISSUE TITLE
some maps (with the placing of food spawns) encourage random results.

### ISSUE THREAD

**Issue by ashokae** [aichallenge/aichallenge#246]
Some maps have spots of high food spawn concentrations at the start. for example height_map_8. At the start ,bots are blind due to fog of war, so if some bot blindly moves in the direction of such a spot, that bot would have a higher chance of winning the game on a stroke of luck.

Ideally food should be placed evenly distributed across the map at the start. During the play, food spawns should be again placed randomly one by one. (without placing chunks of food in one location) 

for instance, locations (row:15-17, col:45-47) in the following map. although the rest of game has no bearing on this particular issue. Here, 3 food spawns are clustered together, I have seen instances where 4 are close by. Note that it is not an issue to have lof of food spawns around and very close to an ant at the start. This become an issue only when an ant has to blindly navigate for food. 

http://aichallengebeta.hypertriangle.com/visualizer.php?game=161822&user=264

**Comment by McLeopold** [comment]
That cluster of three was placed on the map twice.  Both bots had the same opportunity.  Part of a good bot should be quick exploration of the area.

We aren't going to bias food placement by anything on the map, especially other food.
