### ISSUE TITLE
skill level changes look inconsistant

### ISSUE THREAD

**Issue by ashokae** [aichallenge/aichallenge#248]
Please ignore this issue if it is a case of incorrect understanding of the Trueskill behavior from my part. I'm not 100% sure whether this is a issue but it sure looks suspicious.

6 Sep 2:38  94.52 –   1st-GreenTea2nd-apertu3rd-phillc4th-matteo_solstice5th-TrumpeT  1st of 5    symmetric_32    451 turns » Won at 404 »

5 Sep 19:55 94.48 ↑   1st-GreenTea2nd-Speedy_Consoles3rd-zounds4th-UvAntsBeta5th-Obeleh   1st of 5    symmetric_30    633 turns » Won at 389 »

The game listed at top has earned GreenTea only 0.04 points in skill. here's the link for the game http://aichallengebeta.hypertriangle.com/visualizer.php?game=162951&user=21

the game in qsn included the bot TrunpeT as well, even though GreenTea has beaten Trumpet as well as 3 other bots, it got only 0.04 in skill. Now, if we look at bots who were rated higher than GreenTea (sir_macelon, revolt, kadiyaa, FlagCapper, Mathis) they are getting more in skill level for even beating TrumpeT alone. some of those bots have played more games than GreenTea as well. So it is confusing why the skill level increase is so low for this case. 

Surely, skill points earned for defeating a bot X and few others has to be bit higher than defeating only X ? 

May be this is related to the earlier logged issue of winning against weaker bots reducing skill points. (note the presence of the bot phillic in the game. In both examples given for that earlier issue, that bot was present). So can it be that GreenTea got more points for beating TrumpeT bot they got offset by negative marks it may have earned for beating phillic ? (if that's the case indeed, this issue is a duplicate of the earlier one)

**Comment by McLeopold** [comment]
GreenTea is near the top of the maximum skill points.  He is expected to win almost everything and can't really gain much from any match, only hold a high skill.

Using the following sql I can get the before and after numbers:

```
select u.username, mu_before, sigma_before, game_rank, game_score, mu_after, sigma_after
from game_player gp
inner join user u
    on gp.user_id = u.user_id
where game_id = 162951
order by game_rank;

+-----------------+-----------+--------------+-----------+------------+----------+-------------+
| username        | mu_before | sigma_before | game_rank | game_score | mu_after | sigma_after |
+-----------------+-----------+--------------+-----------+------------+----------+-------------+
| GreenTea        |   99.7549 |      1.75884 |         0 |       1582 |  99.8044 |     1.75985 |
| apertu          |   72.7785 |      1.33742 |         1 |        142 |  73.0889 |     1.33688 |
| phillc          |   74.5645 |      1.32904 |         2 |        114 |  74.7104 |     1.32752 |
| matteo_solstice |   78.7613 |      1.35215 |         3 |         88 |  78.7132 |     1.34987 |
| TrumpeT         |   90.3937 |      1.39725 |         4 |         51 |  89.9142 |      1.3947 |
+-----------------+-----------+--------------+-----------+------------+----------+-------------+
```

Acording to the microsoft online calculator at http://atom.research.microsoft.com/trueskill/rankcalculator.aspx we should have gotten this:

```
99.756 1.760
73.607 1.299
75.034 1.287
78.715 1.307
89.021 1.351
```

These numbers are a bit off, but the general direction of each change is correct.  Those that should have gained did and those that should have lost did.  We actually gave GreenTea more skilll points than we should have.
