### ISSUE TITLE
More install scripts

### ISSUE THREAD

**Issue by amstan** [aichallenge/aichallenge#25]
There's a few places where stuff has to be compiled.

We should go through them and make python install scripts for them.

Places of the top of my head:
- Sample Bots Packaging
- Visualizer
  - Javascript minification
  - Java visualizer compiling

**Comment by amstan** [comment]
I should really split this in 2 issues.

**Comment by Janzert** [comment]
These are both these tasks now have automated ways to do them (Makefile for the starter bots and ant deploy for the visualizer) and are integrated with the server setup script.
