### ISSUE TITLE
Eclipse projects?

### ISSUE THREAD

**Issue by mleise** [aichallenge/aichallenge#252]
First of all, let me say that I know that a source code repository is supposed to be environment and IDE agnostic. I don't want to change that.
I use Eclipse for projects in D, JavaScript and Java and from our .gitignore file I read that at least on other developer uses Eclipse PyDev. So probably this extends to many of us on Windows/Linux/MacOS X.
I propose that we add a directory 'eclipse_projects' to github, that contains ready to use projects that everyone can checkout into their Eclipse workspace, while keeping bash scripts, ant files and Makefiles around, that build the project from the command line and on the server. It would be purely optional, but comes with some benefits.
- I don't have to create a new PyDev project to browse/edit the Python code when someone else has a working one already. Same goes for others making changes to the visualizer, website etc...
- Most Eclipse language plugins are good add finding suspicious looking source code. As an example it found some unescaped > and & in html code and missing closing tags. These show up as warning automatically.
- Tab/space settings can be stored in the project, to avoid accidental wrong indentation. There are other optional rules like warnings when a variable is shadowed, that turn on warnings for certain coding styles and help in creating consistent source code among several developers.
- Launch configurations can be stored with the project. (helps with the question how to do a test run, like play_one_game)
- Not only others, but you yourself can checkout the project on a different machine and have the correct project settings.

This turned a bit into an advertising of Eclipse and associated projects, but if I had that in mind the list would be longer ;-)
So I hope I haven't upset the users of NetBeans, Emacs, Code::Blocks, Visual Studio and all the other editors and IDEs.

**Comment by Janzert** [comment]
These were added
