### ISSUE TITLE
Let bots get to know if they are leading the game or not

### ISSUE THREAD

**Issue by sir-macelon** [aichallenge/aichallenge#255]
Currently it is almost impossible for a bot to know what are the actual ranks in a game.
Even if it is able to see every tile on the map, it will never get to know what are the opponents scores.
So when approaching the game turn limit the bot doesn't know how it is performing and cannot plan its strategy accordingly.
This leads to more guessing game, which increases the luck factor about the final ranks.

What would help is just a simple line of information provided by the engine every turn telling the bot if it is currently leading the game (in terms of score of course) or not.

I don't believe this change would spoil any of the game ideas.
Shouldn't be hard to implement either.
It would make the rankings more consistent and solve the problems with scoring system as it wouldn't matter that much any more.

Issue to be discussed and approved.

**Comment by Janzert** [comment]
Closing since the game has changed since it was filed and I think it could very possibly provide bad incentives now.
