### ISSUE TITLE
User profile page next game prediction time (very) innaccurate.

### ISSUE THREAD

**Issue by ChrisHines** [aichallenge/aichallenge#257]
The next game prediction time on the user profile page is (very) innaccurate.

Not only does it frequently show negative times, but it consistently underestimates the time. My account (http://aichallengebeta.hypertriangle.com/profile.php?user=815) is currently getting in a game about once an hour, yet just after a game the predicted next game is typically about 30 minutes.

**Comment by McLeopold** [comment]
dup of issue #194
