### ISSUE TITLE
Erlang starter package

### ISSUE THREAD

**Issue by gattschardo** [aichallenge/aichallenge#266]
I've written a starter package for erlang which implements all the must have and a couple of the optional helper functions. It passes the test_bot.sh script successfully on my machine. It doesn't run properly on the beta server though because the options I suggested for compile.py are broken. The best way to fix it would be to switch to using the ExternalCompiler, that is

```
TargetCompiler(comp_args["Erlang"][0], targets["Erlang"], ""))]
```

should be changed to

```
ExternalCompiler(comp_args["Erlang"][0]))]
```

Once compiling works the way it should, I'll verify that the package works properly on the server, too and then upload the code.

**Comment by Janzert** [comment]
This should be fixed. If you could test it and maybe post your starter bot would be great.

**Comment by gattschardo** [comment]
It is partly working, now... when I submit code consisting of just one file (this being called `my_bot.erl'), it compiles and runs just fine. Whenever I submit something with more than one .erl file (including my_bot.erl, of course), I get a compile error though, and it says

```
Output file my_bot.beam was not created.
```

If you know how to fix compilation of multiple files, that would be great. By looking at compile.py I think it should do that already, since we are wildcarding for `*.erl'? Otherwise I could also go and put all the starter package code into the my_bot module, and we only allow one code file for erlang submissions. That would be a bit awkward, but I have really no idea why this compilation gives us so many problems and can't really tell you what's going on, here :(

**Comment by Janzert** [comment]
Could you post the exact command as you would run it to compile a multi-file submission? Basically after reading the erlc documentation it looked like it just needed all .erl files given as arguments to one erlc command (e.g. "erlc my_bot.erl extra_file1.erl extra_file2.erl") so that's what I have the compiler script doing now. Having access to the actual starter bot would also make it a little easier to test.

**Comment by gattschardo** [comment]
The example you give should work fine (and does indeed on my machine). The option we were going for before, which would have been calling "erlc file.erl" for all files in the current dir ending in .erl will also work. Both don't seem to work on the server though, for whatever reason. I just tried the new way, it still says my_bot.beam was not created (and still works fine for a single file).

I've uploaded the code, so you can have a look:

```
http://paste.xinu.at/BRGP/
```

This will also produce a file listing for . on stderr, and will report each variable it read from the game and write each command it gives to the game to stderr. For the one file-test example that compiles and gives a listing of the current dir to stderr (but does not actually play the game, so it'll time out on the test) see: 

```
http://paste.xinu.at/yjb/
```

I've really no idea what's going on here. I'm probably overlooking something really obvious right now, but whatever it is...

**Comment by Janzert** [comment]
I don't think it is the cause of the problem above, but I'm getting an error when I try and compile the bot manually:
$ erlc my_bot.erl map.erl ants.erl
./ants.erl:144: function min/2 undefined
./ants.erl:145: function min/2 undefined

Not sure how to check the erlc version but erl startup looks like this:
$ erl
Erlang R13B03 (erts-5.7.4) [source] [64-bit] [rq:1] [async-threads:0] [hipe] [kernel-poll:false]

Eshell V5.7.4  (abort with ^G)
1> 

It does look like compiler errors are output to stdout insteand of stderr though so I'm going to have to do some reworking for that.

**Comment by gattschardo** [comment]
Okay, thanks for that information! It is just a minor incompatability between ubuntus erlang version (R13B, as reported by you) and mine (R14B). I totally expected to see compiler error messages, which is why I did not even think about that. The fixed starter package is available here:

```
http://paste.xinu.at/3X8A/
```

It still prints debug info to stderr, but I guess that won't be a problem (and anybody knowing erlang should understand it does that from the source anyways). So we now have a working starter package, finally, wohoo! :D

It would be nice to fix the compiler error messages output long-term, though :)

**Comment by kostikvento** [comment]
Sorry for my intervenience, but could you please tell me what command should one pass to playgame.py script in order to use the erlang bot, instead of pythonic "python MyBot.py"?

**Comment by kostikvento** [comment]
Well, I found it myself :) it is "erl -noshell -pa /home/user/full/path/to/ai_folder -s my_bot start -s init stop".

**Comment by gattschardo** [comment]
Glad you found that so quick. If there's anything you don't like about the package (or even bugs), please let me know!

Btw, you can leave out the "start", since erl will call this by default when no function is given, so

```
erl -noshell -pa <path> -s my_bot -s init stop
```

**Comment by kostikvento** [comment]
Thanks for your reply. So far, your starter package is doing good :)

I am kind of newbie in Erlang, so my questions may look naïve.
The next one is: what files should the submission package contain? Source files only (i.e. *.erl, *.hrl and the like) or compiled *.beam files, too? What is the AI Challenge compiling procedure for Erlang-driven bots?

**Comment by kostikvento** [comment]
Well, I found the answer again :) A link to compile.py was posted in the challenge forum, so it is clear now that *.erl files suffice.
