### ISSUE TITLE
Game results on user profiles do not match the visualizer.

### ISSUE THREAD

**Issue by ChrisHines** [aichallenge/aichallenge#269]
In this game:  http://aichallengebeta.hypertriangle.com/visualizer.php?game=1152&user=5 the visualizer shows the game ending with InsaneMalkavian ranked #1 with 35 points (23 + 12 bonus), and ChrisH ranked #2 with 27 points ranked #2.

But on the user profiles pages and the game list page, that game displays ChrisH as getting rank 1 and InsaneMalkavian as rank 2.

**Comment by McLeopold** [comment]
This is a visualizer issue.  The last score in the score history displays the the scores with the bonus.  The visualizer is adding the bonus in.  The ranks part of the replay is being ignored.
