### ISSUE TITLE
Food spawning on hills

### ISSUE THREAD

**Issue by RVeerdonk** [aichallenge/aichallenge#272]
Not sure if this is intentional, but I have seen one instance of food spawning on an available ant-hill.

If only I could remember where I saw it ...

**Comment by McLeopold** [comment]
It should not be happening.  If you can find a link to a game, that would be helpful.  I will double check the code to make sure it doesn't happen.

**Comment by RVeerdonk** [comment]
The function "get_symmetric_food_sets" creates the symmetrically equivalent food-sets (L1217). There is a check that skips "initial_ant_list" locations (L1252). Those in turn are initialized with all the hill locations during initialization (L129). So, I agree with you that this should not happen. If I see it happen again, I'' post a link here.

**Comment by RVeerdonk** [comment]
Here are a few examples (there are multiple equivalent positions on each map for each link):
http://aichallengebeta.hypertriangle.com/visualizer.php?game=2550&user=49&turn=15&row=15&col=67
http://aichallengebeta.hypertriangle.com/visualizer.php?game=2550&user=49&turn=323&row=22&col=59
http://aichallengebeta.hypertriangle.com/visualizer.php?game=2651&user=49&turn=832&row=32&col=72  http://aichallengebeta.hypertriangle.com/visualizer.php?game=2744&user=49&turn=105&row=88&col=38
http://aichallengebeta.hypertriangle.com/visualizer.php?game=2744&user=49&turn=387&row=75&col=55

**Comment by RVeerdonk** [comment]
more examples:
http://aichallengebeta.hypertriangle.com/visualizer.php?game=1049&turn=622&row=21&col=6
http://aichallengebeta.hypertriangle.com/visualizer.php?game=409&turn=797&row=9&col=121
http://aichallengebeta.hypertriangle.com/visualizer.php?game=423&turn=543&row=109&col=77
http://aichallengebeta.hypertriangle.com/visualizer.php?game=445&turn=173&row=32&col=22
http://aichallengebeta.hypertriangle.com/visualizer.php?game=507&turn=2&row=19&col=2
http://aichallengebeta.hypertriangle.com/visualizer.php?game=512&turn=599&row=66&col=39
http://aichallengebeta.hypertriangle.com/visualizer.php?game=534&turn=2&row=65&col=62
http://aichallengebeta.hypertriangle.com/visualizer.php?game=549&turn=346&row=21&col=6
http://aichallengebeta.hypertriangle.com/visualizer.php?game=574&turn=173&row=4&col=55
http://aichallengebeta.hypertriangle.com/visualizer.php?game=659&turn=2&row=6&col=24
http://aichallengebeta.hypertriangle.com/visualizer.php?game=694&turn=2&row=63&col=31
http://aichallengebeta.hypertriangle.com/visualizer.php?game=721&turn=864&row=17&col=106
http://aichallengebeta.hypertriangle.com/visualizer.php?game=750&turn=73&row=76&col=21
http://aichallengebeta.hypertriangle.com/visualizer.php?game=785&turn=349&row=7&col=58
http://aichallengebeta.hypertriangle.com/visualizer.php?game=787&turn=191&row=32&col=16
http://aichallengebeta.hypertriangle.com/visualizer.php?game=805&turn=907&row=104&col=109
http://aichallengebeta.hypertriangle.com/visualizer.php?game=812&turn=596&row=10&col=46
http://aichallengebeta.hypertriangle.com/visualizer.php?game=856&turn=59&row=16&col=87
http://aichallengebeta.hypertriangle.com/visualizer.php?game=870&turn=184&row=18&col=6
http://aichallengebeta.hypertriangle.com/visualizer.php?game=906&turn=2&row=16&col=141
http://aichallengebeta.hypertriangle.com/visualizer.php?game=907&turn=663&row=73&col=70
http://aichallengebeta.hypertriangle.com/visualizer.php?game=927&turn=2&row=110&col=120
http://aichallengebeta.hypertriangle.com/visualizer.php?game=930&turn=179&row=45&col=58
http://aichallengebeta.hypertriangle.com/visualizer.php?game=954&turn=742&row=86&col=111
http://aichallengebeta.hypertriangle.com/visualizer.php?game=978&turn=114&row=131&col=125
http://aichallengebeta.hypertriangle.com/visualizer.php?game=1131&turn=730&row=16&col=23
http://aichallengebeta.hypertriangle.com/visualizer.php?game=1154&turn=97&row=98&col=28
http://aichallengebeta.hypertriangle.com/visualizer.php?game=1171&turn=423&row=44&col=68
http://aichallengebeta.hypertriangle.com/visualizer.php?game=1213&turn=2&row=63&col=0
http://aichallengebeta.hypertriangle.com/visualizer.php?game=1247&turn=992&row=82&col=36
http://aichallengebeta.hypertriangle.com/visualizer.php?game=1301&turn=726&row=74&col=39
http://aichallengebeta.hypertriangle.com/visualizer.php?game=1324&turn=108&row=62&col=58
http://aichallengebeta.hypertriangle.com/visualizer.php?game=1390&turn=125&row=52&col=6
http://aichallengebeta.hypertriangle.com/visualizer.php?game=1490&turn=90&row=20&col=56
http://aichallengebeta.hypertriangle.com/visualizer.php?game=1515&turn=2&row=23&col=23
http://aichallengebeta.hypertriangle.com/visualizer.php?game=1531&turn=514&row=50&col=18
http://aichallengebeta.hypertriangle.com/visualizer.php?game=1542&turn=239&row=45&col=45
http://aichallengebeta.hypertriangle.com/visualizer.php?game=1556&turn=109&row=68&col=68
http://aichallengebeta.hypertriangle.com/visualizer.php?game=1559&turn=137&row=39&col=43
http://aichallengebeta.hypertriangle.com/visualizer.php?game=1677&turn=478&row=72&col=77
http://aichallengebeta.hypertriangle.com/visualizer.php?game=1913&turn=829&row=66&col=78
http://aichallengebeta.hypertriangle.com/visualizer.php?game=1990&turn=131&row=104&col=36
http://aichallengebeta.hypertriangle.com/visualizer.php?game=2005&turn=379&row=66&col=17
http://aichallengebeta.hypertriangle.com/visualizer.php?game=2038&turn=973&row=9&col=9
http://aichallengebeta.hypertriangle.com/visualizer.php?game=2163&turn=140&row=111&col=65
http://aichallengebeta.hypertriangle.com/visualizer.php?game=2169&turn=573&row=123&col=87
http://aichallengebeta.hypertriangle.com/visualizer.php?game=2194&turn=25&row=43&col=6
http://aichallengebeta.hypertriangle.com/visualizer.php?game=2404&turn=314&row=39&col=72
