### ISSUE TITLE
Save current state as map-file from visualizer

### ISSUE THREAD

**Issue by RVeerdonk** [aichallenge/aichallenge#274]
It would be extremely useful for bot-debugging purposes if one could stop a game-replay in the visualizer at some interesting turn and save the state in map-format.

**Comment by mleise** [comment]
This is in deed useful. I don't want to add more buttons to the visualizer though. Menus would be one way to hide the complexity away. I'll keep the issue open. Maybe we will come back to it again or I get a flood of people requesting this feature.

**Comment by mleise** [comment]
This feature is now implemented in the visualizer. It can also be used on the command-line via a switch to visualizer.jar.
