### ISSUE TITLE
bot input specification

### ISSUE THREAD

**Issue by orian** [aichallenge/aichallenge#280]
Hi,

I think that would be very helpful to add more specific bot input:
e.g.:
    "loadtime"       # in milliseconds, int, 0 < loadtime < 2^31-1
    "turntime"       # in milliseconds, int, 0 < loadtime < 2^31-1
    "rows"           # number of rows in the map, int, 0 < loadtime < 500
    "cols"           # number of columns in the map, int, 0 < loadtime < 500
    "turns"          # maximum number of turns in the game, int, 0 < loadtime < 10000
    "viewradius2"    # view radius squared, int, 0 < loadtime < 2^31-1
    "attackradius2"  # battle radius squared, int, 0 < loadtime < 2^31-1
    "spawnradius2"   # spawn radius squared, int, 0 < loadtime < 2^31-1
    "player_seed"    # seed for random number generator, useful for reproducibility, string

I'm not sure about values, but it should like somehow similar.

**Comment by McLeopold** [comment]
Added note that all numbers will be 32bit signed integers.  I'm not willing to specify lower limits, even though it is 99% probably they will be correct.
