### ISSUE TITLE
NodeJS upgrade required?

### ISSUE THREAD

**Issue by mleise** [aichallenge/aichallenge#286]
http://ai-contest.com/forums/viewtopic.php?f=25&t=1484

Seems like with the version listed as supported, bots can not be developed on Windows.

**Comment by Janzert** [comment]
I'm not terribly familiar with nodejs but I'd rather stick with their stable version. If someone that _is_ familiar with it can say that unstable isn't really that unstable then I could probably be persuaded otherwise.

**Comment by McLeopold** [comment]
On win7-64, node v0.5.8 and v0.5.9 are unstable within the sandbox framework.  v0.5.7 and below works good.  All versions work when just redirecting a bot input file to the program.

I would recommend keeping the nodejs version on the workers at stable, and letting windows users know to avoid the higher unstable versions.

**Comment by mleise** [comment]
Can you post this in the forum thread above as well? It may be the first place that Windows users look for help.

**Comment by voxpelli** [comment]
Odd version numbers of NodeJS are the unstable ones so if one only wants to support stable versions then 0.4 was the right one until the release of 0.6. Now that 0.6 is released though an update would be nice.
