### ISSUE TITLE
specification.php crashes rendering

### ISSUE THREAD

**Issue by amstan** [aichallenge/aichallenge#292]
http://aichallenge.org/specification.php

Using chromium.

I can't see the side bar menu either.

**Comment by Janzert** [comment]
For some reason the angle bracket escaping using a \ around the word object in:

map <object> This object contains the map. 

In the replay format spec was inserting actual < > characters in the html source thus opening an <object> tag and breaking the page.

I changed it to html entity escaping directly and it is working ok now.
