### ISSUE TITLE
Add password reset mechanism

### ISSUE THREAD

**Issue by Janzert** [aichallenge/aichallenge#294]
Best way to do this is probably to send an email with a new 'confirmation' coded link to a page that would then allow the password to be changed.

**Comment by syst3mw0rm** [comment]
So we will ask user to fill his email id and then send the 'confirmation' coded link..
I would like to work on this one.

**Comment by Janzert** [comment]
Pretty much. Basically two pages need to be created.

The first should be linked from the login page with a password reset link. It should ask for the username, generate and store a new confirmation code in the database and then send an email to the address in the user's profile with a link back to the second page that also contains the confirmation code in the link. Generating a confirmation code, creating a link with it and sending an email can all be seen in the current registration.

The second page should take the confirmation code as a GET parameter, check that it is valid, and add it as a hidden field in a form asking for the new password (using password inputs and input twice to confirm it from the user). The form can then submit as a post method (back to the same page or a different page if you want). After receiving the form, the server can check the received data and set the password of the user to the new one just received.

**Comment by McLeopold** [comment]
Mostly done.
