### ISSUE TITLE
Google Apps for aichallenge.org

### ISSUE THREAD

**Issue by amstan** [aichallenge/aichallenge#295]
Set up email lists too.

It would be nice if we could merge the 2 domains google apps wise.

**Comment by amstan** [comment]
@Janzert we need this for launch? Or can i do features rollout?
Maybe i should ask @j3camero.

**Comment by Janzert** [comment]
Not strictly necessary for launch. But until it is in place all contest emails will be sent with a from address of janzert@janzert.com. So it would be good to get it as soon as we can.

**Comment by j3camero** [comment]
I can set this up right now. Let me know what we need.

Is the plan to send contest email from Google Apps? We tried that last time
and we got blocked fairly quickly. If we want to send contest mail through
Gmail's servers, do we have a plan for not getting blocked?

**Comment by MaximeCheramy** [comment]
Why not using a dedicated SMTP server ? You can configure any gmail account to say that your dedicated server is allowed to send email using your account (if you don't configure it, your email might be considered as spam).

**Comment by amstan** [comment]
We're still sending through amazon. But we still need an inbox to receive all the replies.

@j3camero: How do you merge the 2 domains though?
Can you also make me a domain admin on that?

**Comment by Janzert** [comment]
To expand slightly on what amstan said. Amazon (wisely) requires a valid and verified from address on emails sent. For the beta and currently this has just been my personal address.
The highest volume of messages coming back are simply bounces from people that enter an invalid address, but there are some legitimate questions as well. I think the best place to end up at eventually would be to use a email list that the staff could monitor.
I'm also starting to think that the semi-standard practice of requiring double entry of the email address in the registration form might be a good idea.
