### ISSUE TITLE
Point ai-contest.com to the new server

### ISSUE THREAD

**Issue by amstan** [aichallenge/aichallenge#301]

**Comment by j3camero** [comment]
Done. ai-contest.com now points to 107.20.156.231, the same as aichallenge.org.

**Comment by amstan** [comment]
Problem is that we're not going to use that server yet, it's another server that we'll use for launching.

**Comment by j3camero** [comment]
Okay, then we will have to update ai-contest.com along with
aichallenge.orgagain.
