### ISSUE TITLE
Set up Google Analytics for aichallenge.org

### ISSUE THREAD

**Issue by j3camero** [aichallenge/aichallenge#302]
Google Analytics lets us see how much traffic we're getting in more or less real time. It is currently set up for ai-contest.com, the old domain name. I need to make sure that it also works for the new domain name, aichallenge.org.

**Comment by Janzert** [comment]
It almost certainly is. It seemed to correctly record the hacker news surge yesterday

**Comment by amstan** [comment]
@j3camero: i need you to set a new key if you want aichallenge.org separately. We're currently using the key from ai-contest.com.

Also, can i have admin for that?

**Comment by j3camero** [comment]
Alex Stan is now an admin on the Google Analytics for ai-contest.com, which also seems to include the traffic for aichallenge.org.
