### ISSUE TITLE
Incorrect build command for OCaml starter

### ISSUE THREAD

**Issue by VictorNicollet** [aichallenge/aichallenge#310]
Hello,

The OCaml README.md mentions `ocamlbuild MyBot.native`, the correct build command should be `ocamlbuild -lib unix MyBot.native`. Possible solutions: fix the README.md or add an ocamlbuild configuration file to the package.

**Comment by amstan** [comment]
What if you want to compile on windows?

Can you submit a pull request for this?

**Comment by VictorNicollet** [comment]
`-lib unix` is supported on Windows (actually, only a subset is), and if it wasn't, then the package wouldn't work on Windows anyway. From what I recall, the only pieces of `Unix` used are `Unix.gettimeofday ()` which should work cross-platform.

As for the pull request, I would, if I could find the aforementioned README.md in the source tree...
