### ISSUE TITLE
Ant colors repeat in visualizer

### ISSUE THREAD

**Issue by olexs** [aichallenge/aichallenge#311]
Example: http://aichallenge.org/visualizer.php?game=494&user=871

My bot (olex.s) and ornicar are the same color. Not to mention that the contrast of this color to background is virtually non-existant. Colors used in beta were much, much better.

**Comment by mk0x9** [comment]
+1 for beta colors. Need more ACID and VIVID colors.

**Comment by amstan** [comment]
Fixed.
