### ISSUE TITLE
Game rate not showing correctly in ranking pages

### ISSUE THREAD

**Issue by inoryy** [aichallenge/aichallenge#313]
Currently it's showing game count instead.

Here's the code that's most likely the cause:
https://github.com/aichallenge/aichallenge/blob/epsilon/website/sql.php#L152

**Comment by Janzert** [comment]
game rate is the number of games played in the last 24 hours. Since the contest has been running less than 24 hours they will be the same at this point.

**Comment by inoryy** [comment]
But why does it state differently <a href="https://github.com/aichallenge/aichallenge/blob/epsilon/website/ranking.php#L271">in the explanation</a>?
Also why is it displayed differently in the profile page (like in the explanation)

**Comment by Janzert** [comment]
The definition was changed a while back, apparently the description was never updated. Should be fixed now. The rate on the profile page is a completely different measure (i.e. it measures the number of players that play a game per minute globally in the contest).

**Comment by Janzert** [comment]
and now I see you were probably referring to the submission game rate in the recent submissions table. That does appear to still use the old definition.

**Comment by inoryy** [comment]
Yeah, I was referring to <a target="_blank" href="http://img14.imageshack.us/img14/5592/screenshot1ai.png">this one</a>
