### ISSUE TITLE
Ignore warnings when compiling C++

### ISSUE THREAD

**Issue by AlvinMinring** [aichallenge/aichallenge#321]
gcc warnings are considered to be compilation errors by the server - presumably, they are output on stderr and that's what the compiler worker reads.

But we don't need warnings on the server, so the quick fix would be to compile with the -w option.

**Comment by Janzert** [comment]
The downside would be, how many of those warnings _are_ actually catching things that would cause the submission to occasionally crash?

As a side note, we've treated warnings as compilation failures in previous contests this isn't anything new.

**Comment by AlvinMinring** [comment]
> The downside would be, how many of those warnings are actually catching things that would cause the submission to occasionally crash?

It depends a whole lot on how much testing was performed locally before the submission was uploaded.
If the submission has not been correctly tested, the user will probably just fix the warnings until the submission compiles alright, and crashes nonetheless.
If the submission has been correctly tested (as should be the case), I'd say none of them.

For instance, using hash_map raises a backward compatibility warning - which I've disabled the ugly way right now. This warning has zero impact on runtime behavior. (As a side note, I'd have liked to use unordered_map instead, but this requires the compilation flag -std=c++0x).

**Comment by McLeopold** [comment]
Another contestant recently had issues with this.  They would have liked to see more warnings.  In the future, I'd like to capture as much error and warning data as possible to display to the user, but allow the bot to compile and compete regardless.

**Comment by amstan** [comment]
Build systems will take care of this in zeta.
