### ISSUE TITLE
Comment is wrong

### ISSUE THREAD

**Issue by tessprime** [aichallenge/aichallenge#33]
From [ants.py](https://github.com/aichallenge/aichallenge/blob/epsilon/ants/ants.py)

```
463         # kill ants with damage > 1
464         for ant in damage:
465             if damage[ant] >= 1:
```

Either the comment or the implementation is wrong. Emphasis on '>' vs '>='.

**Comment by sigh** [comment]
Yeah, code is right damage of 1 should kill. Fixed.
