### ISSUE TITLE
Add debugging features to the visualizer

### ISSUE THREAD

**Issue by amstan** [aichallenge/aichallenge#336]
The contestants want a way to make the visualizer display lines, circles, shade blocks and a bunch of other things. I think using the visualizer would be much helpful than each contestant inventing some makeshift map output functions to debug their bots(ex: testing how the bot remembers terrain).

[Forums Post](http://aichallenge.org/forums/viewtopic.php?f=25&t=1633&p=9995)

**Comment by j-h-a** [comment]
I forked the repo to work on this feature here: https://github.com/j-h-a/aichallenge

**Comment by amstan** [comment]
@j-h-a: Good job
