### ISSUE TITLE
playgame.py incorrectly handles working directories and commands

### ISSUE THREAD

**Issue by Storyyeller** [aichallenge/aichallenge#341]
When passed a command invoking an executable in a different directory, playgame.py incorrectly splits the path and attempts to use the executable name relative to the detected working directory. But according to the official documentation of Subprocess, this is incorrect.

[quote]If cwd is not None, the child’s current directory will be changed to cwd before it is executed. Note that this directory is not considered when searching the executable, so you can’t specify the program’s path relative to cwd.[/quote]

Anyway, this bug can be fixed by changing line 262 of playgame.py from 
[code]return wd, ' '.join(new_cmd)[/code] 
to 
[code]return wd, cmd[/code]

**Comment by Zannick** [comment]
That will work for executables, but not for any languages where the executable is not the compiled binary, eg. Java.

When the executable is 'java', then the argument passed to it can be relative to the cwd, eg. 'MyBot.jar' in 'java -jar MyBot.jar'. When the executable is the binary, then yes, we need to pass the original path to subprocess, if that's how we're launching.

Unfortunately, while I can easily fix this function to do the proper thing for that case (without additional changes), it will break the secure mode of running, where the bots are chrooted to the proper directory, and thus should use the path relative to the cwd. So we have to do it in such a way that it only truly changes for the nonsecure case. 

(Incidentally, this code is wrong anyway: the i == 0 case hits only the very last argument in the cmd, not the first one.)

**Comment by Zannick** [comment]
Fixed with 86d12b32a2.
