### ISSUE TITLE
Work on more permanent urls

### ISSUE THREAD

**Issue by amstan** [aichallenge/aichallenge#342]
With our archival efforts, I also want to make sure that external links to the current contest will remain working.

A bad example I saw just today is http://quotenil.com/Planet-Wars-Post-Mortem.html, he's linking at the rankings page, but his name is not at the top anymore, in fact it's the wrong contest he links at.

The idea is to keep each contest on its own subdomain. Subdomains will be named with a short to the point name. Example: tron, ants, planetwars, rps. If there's more than one contest with the same name it could have a 2 at the end (tron2).

Ideally the homepage should stay the same, aichallenge.org. Forums should be moved to a subdomain(forums). The moment a user clicks from aichallenge.org to an internal link(rankings for example), he will be redirected(permanent) to the current contest(ants.aichallenge.org). He will be free to link to there at any time, without any fear that links will break.

Given that we broke a lot of planetwars links, and ai-contest.com was mainly used for that. We could assume all requests that are not to the homepage or forums to ai-contest.com are supposed to be for planetwars. This could apply to csclub.uwaterloo.ca/contest for tron.

When launching new contests we could use a beta. subdomain prefix for testing.

The only duplicate content should be aichallenge.org/frontpage with mostrecent.aichallenge.org/frontpage. Any ideas on how to fix this. The older contests will all have their own old homepages(with the congratulations).

Proposed redirect rules:
- aichallenge.org/forum[s]?/(.*) => forums.aichallenge.org/$1
- aichallenge.org/(.+) => ants.aichallenge.org/$1
- ai-contest.com/forum[s]?/(.*) => forums.aichallenge.org/$1
- ai-contest.com/(.*) => planetwars.aichallenge.org/$1
- csclub.uwaterloo.ca/contest/forum[s]?/(.*) => forums.aichallenge.org/$1
- csclub.uwaterloo.ca/contest/(.*) => tron.aichallenge.org/$1

**Comment by amstan** [comment]
How easy is it to change the urls from the replays? I think they all go to aichallenge.org now.

**Comment by Janzert** [comment]
I like the overall scheme. Given that we're now in the middle of the ants contest I'd rather not make the change to ants.aichallenge.org until after the contest is over. An alias of ants.aichallenge.org would be fine immediately though.

**Comment by amstan** [comment]
I disagree. We should be getting the change now. Or else everyone who links to the current contest will have their links broken when it's over.

**Comment by DanielVF** [comment]
+1

A subdomain per contest is the way to go. Allows you to make a static version of the site later on, and put it up on S3 for long term archiving.

**Comment by amstan** [comment]
The archive servers are all at $contestname.aichallenge.org.
The main page needs to contain info about the contest in general and links to the current and past contests. TODO
