### ISSUE TITLE
Update contest rules

### ISSUE THREAD

**Issue by Janzert** [aichallenge/aichallenge#344]
The current rules are essentially unchanged from the last few contests. There's probably more but a couple that I'm looking at right now that really need updating are:
- You may not write to files. You may however read from files within your submission directory, which will be the current directory.
- Use of multiple processes or OS threads are prohibited.

Neither of these are things we actually do or can prohibit because there are language _runtimes_ that break them. The two examples off the top of my head are mono writing files and java spawning processes. Java for sure and IIRC mono both crash if they aren't allowed to do so.

Instead I think we should have something along the lines of:
- setting a smallish limit (10MB?) on the size of files written and explain that they won't be preserved past the end of the game
- setting the limit on threads/processes to what is required by the runtimes and prohibit active computation on more than one at a time

**Comment by McLeopold** [comment]
+1

**Comment by amstan** [comment]
Sounds good.

**Comment by mleise** [comment]
+1, but let me give a real answer. I think details on how large the written files may become don't need to be in the rules. There is simply no point in writing to files. They are not preserved and we grant way more RAM than what 10 MB slow swap would represent. Maybe put it in parenthesis after a simple one-liner, for those that uploaded a bot that writes a log and wonder if it will be disqualified or crash :)
"Active computation" sounds good at first, but I wonder what happens with Java's JIT compiler. Assuming not all classes are used (and compiled) in turn "0", this may result in additional cores used as soon as classes for path finding, a math library etc. are accessed. Otherwise it is a good idea to simply check for wall_time >= cpu_time. If you used more cpu time than wall time, you must have used more than one core actively.

**Comment by Janzert** [comment]
Some concrete rewrites then

Prohibited actions:
-  Entries which are deemed to violate the spirit of fair and sportsmanlike competition will be disqualified without any opportunity for appeal. In particular, memory scanning, intentionally losing games, and behavior conditional on the opponent's identity are prohibited.

To:
-  Entries which are deemed to violate the spirit of fair and sportsmanlike competition will be disqualified without any opportunity for appeal. In particular, memory scanning, manipulating rankings by intentionally losing games, and trying to gather information about your opponent or the game state through means outside of the bot input protocol are prohibited.

File writing:
-  You may not write to files. You may however read from files within your submission directory, which will be the current directory.

To:
-  Files written to will not be preserved between games and a bot found to be writing excessive data (more than 10MB) will be disqualified.

OS threads and processes:
-  Use of multiple processes or OS threads are prohibited.

To:
-  Actively using multiple processes or OS threads is not allowed. Some language runtimes will not operate without using multiple OS threads so we allow the creation of a limited number. But a bot found to be running active computation on more than one will be disqualified.

Attacks on the contest site or software:
-  Any attempt to disrupt the normal operation of the contest software or the contest servers will result in the immediate involvement of law enforcement officials. Our policy is to always prosecute.

(This was apparently mostly put in as a joke)

To:
-  As one would hope would not even need mentioning; any attempt to bypass or disable the contest's security measures, disrupt the contest software or servers, or otherwise interfere with normal operation of the contest is of course prohibited.

**Comment by bjj** [comment]
I suggest you simply use ulimit to enforce the file size you are concerned with.

Regarding threads I would suggest an overhaul of the time limit and thread/processor rules entirely:

Allow some reasonable number of threads (enough for Java, Mono, etc) and let anyone use them with any language.  Remove the wall clock time limitation and instead enforce a CPU time limitation via getrusage().  Bots can use setitimer() to arrange a signal when CPU time is elapsed.  You may wish to enforce a third kind of limit to explicitly describe whether or how much CPU a bot may use while it's waiting for the server between turns.

By measuring CPU time you can be fair to every thread even if they don't get dedicated CPUs.  You can also run many games in parallel on the same CPU set without worrying about how they might interfere with timing.  That should give you improved utilization of your contest resources (or, if you are already doing that, increase the fairness and consistency of the results involving computationally expensive bots).

I'm willing to help with the coding for the server and provide sample timing code in at least a few starter packages.

**Comment by Janzert** [comment]
Thanks for the comments. We're too far into this contest to switch to cpu time at this point but it would be nice to switch to some sort of combination cpu/wall time measurement for the next contest.

These new rules are now in place so I'm closing this issue. Any discussion on means of enforcing them should be separate issues.
