### ISSUE TITLE
C++ compiler flag: -I.

### ISSUE THREAD

**Issue by ZacVawter** [aichallenge/aichallenge#349]
This will allow C++ users to upload code that uses #include <....> notation.  In the case of the boost libraries it is almost impossible to use any piece of it because of the lacking -I.  All of the boost source would have to be modified, and its no trivial task.

Alternatively boost could be installed as a library.

**Comment by Storyyeller** [comment]
I think providing a boost installation would be a better option since it saves on submitted filesize and bandwidth. Of course providing boost and -I is even better!
