### ISSUE TITLE
F# Starter Package

### ISSUE THREAD

**Issue by edusahione** [aichallenge/aichallenge#35]
I recommend F# support to be implemented in this iteration of the contest. A complete implementation process for installing F# on linux with Mono may be found here: http://2sharp4u.wordpress.com/2010/09/03/installing-f-2-0-on-monolinux/. 
I will start working on a starter package this week to help this come to fruition.

**Comment by amstan** [comment]
Cool, follow the guidelines from the [Starter Package Issue](https://github.com/aichallenge/aichallenge/issues#issue/3). Including the part with `setup_worker.py` and `compiler.py`.
