### ISSUE TITLE
Documentation: spawnradius2 is used instead of attackradius2

### ISSUE THREAD

**Issue by johshoff** [aichallenge/aichallenge#352]
For specifying battle rules, the following pseudo-code is used:

```
for each enemy in range of ant (using spawnradius2):
```

On pages http://aichallenge.org/specification.php and http://aichallenge.org/specification_battle.php .

It should read `attackradius2`, not `spawnradius2`. The python code is correct.

(Another detail is that it is slightly confusing that it says "the ant dies" while traversing the ants. It does not die immediately, but only _after_ the loop. A better wording might be "the ant is marked for killing", and then at the end say "all marked ants are killed")

**Comment by Janzert** [comment]
Thanks, should be fixed now.

**Comment by johshoff** [comment]
Thanks for the quick response! Confirmed fixed.
