### ISSUE TITLE
Clojure Starter Package.

### ISSUE THREAD

**Issue by i0cus** [aichallenge/aichallenge#36]
### I would try and make Clojure work in this edition.

While I'm tinkering with Starting Package I'd need to determine the environment setup possibilities. This is actually associated with https://github.com/aichallenge/aichallenge/issues#issue/16 -- can we use a build like leiningen or is setup to be done by hand? There are two ways we can go here.
#### 1. Leiningen -- managed project building, requires Java and Leiningen install script.
- Pros:
  - It manages project dependencies -- JAR libraries needed, including Clojure and Contrib.
  - Which means that Clojure and Contrib versions can be selected by the author.
  - It can also compile the project into one, single uberJAR, that can be run by issuing `java -jar MyBot.jar`
  - Project name, package name, runnable namespace and everything can be changed, as long as `uberjar` target remains valid.
- Cons:
  - The manager can be extended with project dependencies and probably abused.
  - Needs access to network to fetch libraries, so, adding to one above, not really sandboxed.
  - Some space overhead for local artifact repo (per user).

Installation: `wget`ting leiningen sh and running `lein self-install`.

Compiling: `lein uberjar` in directory with `project.clj`.

Running: `java -server -jar MyBot.jar` in directory with `project.clj`.
#### 2. Manual -- requires Java, we provide Clojure & Contrib JARs.
- Pros:
  - No automatic management, all `.clj` and `.jar` files uploaded by user.
  - With set package name, and assuming `our-package-name.core` namespace is always the entry point, it should be relatively easy to set up and utilize.
  - This is the closest to what you already have, should fit in nicely albeit "magic" part.
- Cons:
  - Will fix Clojure and Contrib version at 1.2.
  - Will require `classpath` manipulation to get right, individual per package setup (os.path magic).
  - So assumptions regarding directory layout will be made, so it will not be very flexible.

Installation: Installing JDK, getting Clojure and Contrib JARs, putting them somewhere +rx accessible (`/opt/clojure`).

Compiling: `java -cp classes:src:lib_items:/opt/clojure/clojure.jar -e "(compile 'ai-challenge-ants.core)"`

Running: `java -cp classes:src:lib_items:/opt/clojure/clojure.jar ai_challenge_ants.core`

Thoughts?

**Comment by levand** [comment]
I'm definitely interested this and would be willing to help out in any way you need to make this happen. I know [something about clojure](http://www.amazon.com/Practical-Clojure-Experts-Voice-Source/dp/1430272317) and would be excited to have Clojure as a part of the challenge.

**Comment by i0cus** [comment]
Thanks, levand. The code itself shall not be a problem -- I've actually prepared a rough prototype before creating this issue -- will try to refresh it a little and put on GitHub during the weekend. The deployment, on the other hand, is something to worry about, as outlined above. Nevertheless I think we need to ask the Clojure community for some advice here.

**Comment by ihodes** [comment]
I do think that Leiningen, if at all possible, is the way to go. Correct me if I'm wrong, but it should be sandboxable if the submitters submit the required libraries (might require some tinkering with the .sh, but I think it's doable. 

Additionally, a major problem for this contest has been the startup time in the past. I suggested a solution:

GAME_MASTER: READY
PLAYER1: READY
PLAYER2: READY

So each bot has n seconds to get ready and print ready to stdout before they time out. 

Good luck with this.

**Comment by i0cus** [comment]
I have created a pull request with initial Leiningen support for Clojure and a simple started package.

https://github.com/aichallenge/aichallenge/pull/94

**Comment by i0cus** [comment]
Leiningen requires network to build uberjars (fetching POM files for everything in lib/) and compiling is done offline. The best I can come up with now is doing `lein compile` and then running with:

```
java -cp `lein classpath` my_bot.core
```

which takes over four seconds on my system to print "hello world" from `main-`. Argh.

**Comment by levand** [comment]
What about having users submit an "uberjar", a large binary which contains their code along with all dependencies? Or is user submission of binaries discouraged?

**Comment by i0cus** [comment]
As in the main issue: https://github.com/aichallenge/aichallenge/issues/16 :)

It would be awesome to just submit uberjar and have `java -jar mybot.jar`, but it has not been agreed upon. I would certainly prefer that way, because right now we will most likely timeout before the bot is even started.
