### ISSUE TITLE
Annoying prompt window shows up when typing "i" in search user box

### ISSUE THREAD

**Issue by avdg** [aichallenge/aichallenge#360]
Steps to reproduce

1) Go to a page with a game visualizer (for example http://aichallenge.org/visualizer.php?game=77823 )
2) Focus the user search box under the navigation column on the right of the page
3) Type an "i"

This should pop up a prompt window from the game.

Note (bit irrelevant for this issue): Are these shortcuts btw documented?

**Comment by Zannick** [comment]
I guess the problem is that the visualizer is grabbing keyboard input even when it doesn't have focus.
