### ISSUE TITLE
Hover text on game times not accurate.

### ISSUE THREAD

**Issue by ChrisHines** [aichallenge/aichallenge#366]
The hover text for game times on user profile pages (and maybe elsewhere) does not match the difference between the game time and the "page refreshed at" time displayed at the top of the profile page for a logged in user.

Janzert suspects the hover text is being cached and not recomputed, causing it to be inaccurate.

**Comment by McLeopold** [comment]
That is exactly what is happening.  I could probably inject a time_generated into the html and have javascript keep it up to date.

**Comment by Janzert** [comment]
Simpler might be to just exclude "time ago" from the memcached data and let the php code regenerate it on each request.
