### ISSUE TITLE
dart starter pack "turn    0 bot 0 crashed"

### ISSUE THREAD

**Issue by jackpal** [aichallenge/aichallenge#369]
Now when I upload my dart starter pack it is recognized as a Dart bot. (Hurray!) But I get this error message:

Test Error: compiled, but failed test cases
turn    0 bot 0 crashed

Is there any way I can reproduce this locally (maybe in a VM) to see what's going wrong?

**Comment by amstan** [comment]
./test_bot.sh in the tools package.

**Comment by jackpal** [comment]
Thanks!

I think I figured out the problem -- the dart language support package dart-frogsh-r1499.tgz was missing some needed library files. Shoddy testing on my part.

I have published a new version of that package, dart-frogsh-r1499-2.tgz, that has the missing files, and I have submitted a pull request https://github.com/aichallenge/aichallenge/pull/371
