### ISSUE TITLE
Tutorial script may need to add --viewradius2 55

### ISSUE THREAD

**Issue by jackpal** [aichallenge/aichallenge#375]
Something funny is going on for me in the tutorial: When I run the tutorial on my machine, against my bot, the viewradius2 setting is 77. But I checked the data files for the recorded battles on the web site, and they have a viewradius2 of 55.

That makes a difference because it means my bots see things at different times than the recorded battles do, leading to different behavior.

I find that if I manually add --viewradius2 55 to my tutorial.sh script then everything runs fine.

I am using OSX 10.6.8, I have Python 2.7.2 installed. I can't think of anything strange about my setup.

More information:

(You can verify this by turning on fog-of-war for both visualizers and viewing the size of the fog-of-war circles. You can also verify it by reading the "viewRadius2" setting out of the two simulation's data files.

This web page: http://aichallenge.org/ants_tutorial_step_2.php

plays back this data file: http://aichallenge.org/example_games/tutorial.2.replay

Which has settings "engine_seed": 10843305, "viewradius2": 55

But the tools in http://aichallenge.org/tools.tar.bz2

has a data file: game_logs/0.replay

which has settings "engine_seed": -1261132856773536632, "viewradius2": 77

**Comment by McLeopold** [comment]
The tutorial was made when we were not sure of the view radius.  It is now set at 77 for the official site and should have been updated in all tools.

I will add a note to the tutorial pages explaining the difference.
