### ISSUE TITLE
Broken path in visualizer

### ISSUE THREAD

**Issue by avdg** [aichallenge/aichallenge#383]
After running my games from a relative path, I found an empty window.
This is caused by 1 missing character in the path (see pastebin).

../../../ichallenge must be ../../../aichallenge

Paste bin: https://gist.github.com/1409587
Tested commit: 535b4a83fd7ca1370b573de728ec6ee0c8fe1174

**Comment by McLeopold** [comment]
it's probably in visualize_locally around lines 16-23.  I'd need more info to reproduce your issue.  What is your tree structure and what was the command you used to play the game?

**Comment by avdg** [comment]
Path of my code (executable of bot and custom script): /Users/anthonyvandegejuchte/Documents/source/antsBot/cpp
Path of aichallenge checkout: /Users/anthonyvandegejuchte/Documents/source/aichallenge/aichallenge

I execute the script from the path I code my executable (first path).
