### ISSUE TITLE
Player_seed returned by visualizer for bot input is incorrect

### ISSUE THREAD

**Issue by jcdny** [aichallenge/aichallenge#385]
Sometimes anyway.

For example in game 95405 http://aichallenge.org/visualizer.php?game=95405, the json file has 
player_seed: -3494269252759342425, 
and in the generated input it has 
player_seed -3494269252759342600.  

Probably not that easy to fix unless you carry the seed around as a string since you can't represent int64 as a javascript numeric.

**Comment by McLeopold** [comment]
maybe we should limit the seed amounts to 32bits?

**Comment by jcdny** [comment]
what I do in my own code is take (seed >> 16) ^ (hill_loc \* 1337) and use that which avoids the problem and if I run my bot against itself each one gets a deterministic seed but one that differs based on initial hill location.  I know js numerics are 
supposed to be good for 15 dec digits so seed >> 16 should be safe from truncation.

If someone is testing with a replay and does not know about this it's potentially pretty annoying to track down.
