### ISSUE TITLE
Add GNU/Guile starter package

### ISSUE THREAD

**Issue by NalaGinrut** [aichallenge/aichallenge#387]
Hi, I've written a starter package for Guilers. 
And I sent a pull request. Anyone interested on it?

**Comment by amstan** [comment]
Please continue discussions in the pull request.
Perhaps integrate this in zeta.

**Comment by NalaGinrut** [comment]
So, should I send a pull request for zeta? 
I found zeta branch don't have starter_package directory yet.

**Comment by McLeopold** [comment]
We are between contests.  I'm thinking that we don't really need this for ants, since it is over.  When we get around to the next contest and zeta is actually being worked on, then this might be useful.
