### ISSUE TITLE
Ants visualizer

### ISSUE THREAD

**Issue by amstan** [aichallenge/aichallenge#4]
Assigned to Frontier.
Help from amstan and McLeopold.

**Comment by amstan** [comment]
Issues related to the visualizer:
- [Canvas on IE](https://github.com/aichallenge/aichallenge/issues#issue/8)
- [Interface with the engine](https://github.com/aichallenge/aichallenge/issues#issue/14)

**Comment by amstan** [comment]
Is this done? Can I close this issue?

**Comment by mleise** [comment]
This is done now with the last piece of work being the replays in json format.
