### ISSUE TITLE
Visualizer should allow dragging of maps

### ISSUE THREAD

**Issue by amstan** [aichallenge/aichallenge#40]
I noticed that the maps that antimatroid makes are pretty wrapable, and they look the same regardless of where the wrap line is.

I'm thinking from the point of view of the player. If your bot starts at the middle of the map, you're all good. But if your bot spawns at the side, your ants will wrap a lot and will be rather annoying to track where they are visually.

I propose having a way to scroll the map, so that players that spawn at the sides can move the map to be in the middle.

**Comment by mleise** [comment]
It is on the todo list.

**Comment by mleise** [comment]
And it is done. Today seems to be my 'close-open-issues' day.
