### ISSUE TITLE
JSON feed of game results

### ISSUE THREAD

**Issue by Synesso** [aichallenge/aichallenge#47]
Create a JSON feed of game results. This will allow the wider community to create interesting ways to visualise & analyse game results.

Parameterise the feed such that it can be limited to the results from a subset of bots or languages.

An example JSON feed (flickr) is http://api.flickr.com/services/feeds/photos_public.gne?id=36998705@N00&lang=en-us&format=json

PHP seems to have a JSON module @ http://php.net/manual/en/function.json-encode.php

**Comment by mleise** [comment]
Hi Synesso,
I can see the need to download replays of a certain opponent or your own bot's replays and we are on the way to have 100% json replay files while keeping the file size small. From what I can see the json feeds aren't supported by browsers(?) and don't share a common format, but are useful as a machine readable format (especially cross-site references are possible). The name 'feed' could be misleading here with such a loose format. All in all it is a simple enough addition that could make it into the web site. Technical note: I imagine the replay meta data to be on the feed (players, winner, date) and the actual 'replaydata' to be replaced with a link to the replay file. The list of games should have a 'continue from' option with a game_id, so people can programatically load only the set of games they haven't loaded already. But I'm not to decide on this :-)

**Comment by Synesso** [comment]
Hi mleise. I like all that you have to say on the matter. I agree on separating the meta data and the game results into different resource. I also think the continue from would be useful - and could be date based.
Thanks.

**Comment by Synesso** [comment]
That's what I thought we were saying. One url for a set of games data (which
is most likely defined by range and filtered by bot), and a subsequent call
to get the data for any specific game. Does that align with your thoughts?

**Comment by mleise** [comment]
Whoever tagged this one 'visualizer': This is about listing game replays in a news feed and automated downloads according to filter settings. It has nothing to do with the visualizer.

**Comment by Synesso** [comment]
I'm writing a client to visualise games using this proposed interface. Is the replay format locked down? What I see from running play_one_game.sh is markedly different from https://github.com/aichallenge/aichallenge/wiki/Ants-replay-format

**Comment by mleise** [comment]
You are right, Synesso. I updated the wiki now with information on the JSON format. I don't think anyone will miss the previous format specification, but it can be looked up in the page history.

**Comment by McLeopold** [comment]
This is done.  Try http://aichallengebeta.hypertriangle.com/game_list_json.php?page=1

**Comment by Synesso** [comment]
Exciting news! (but I got a 404)
On 1 Jun 2011 06:48, "McLeopold" <
reply@reply.github.com>
wrote:

**Comment by McLeopold** [comment]
I modified the links, try again

**Comment by Synesso** [comment]
Confirmed, cheers.
