### ISSUE TITLE
python starter bot has bad vision code

### ISSUE THREAD

**Issue by McLeopold** [aichallenge/aichallenge#50]
Need to use the naive vision code for the starter packs.

**Comment by jaycobcoleman** [comment]
It appears that as a result of a copy-paste mistake, input parsed by the setup function in the python starter_pack ants.py for "viewradius2" "attackradius2" and "spawnradius2" are all being assigned to and overwriting loadtime.
                elif key == 'loadtime':
                    self.loadtime = int(tokens[1])
                elif key == 'viewradius2':
                    self.loadtime = int(tokens[1])
                elif key == 'attackradius2':
                    self.loadtime = int(tokens[1])
                elif key == 'spawnradius2':
                    self.loadtime = int(tokens[1])
