### ISSUE TITLE
make engine do sequential bots using signals

### ISSUE THREAD

**Issue by McLeopold** [aichallenge/aichallenge#58]
sequential bots using signals

**Comment by sigh** [comment]
I've implemented this as best I could in the seq branch. What I did was add the ability to pause and resume bots. Then I only allow the bots to run during the time we are listening for moves.

Not sure if this is what you had in mind. Please review, and if it is alright I will merge into epsilon.

**Comment by sigh** [comment]
Janzert reviewed this and gave his OK, so I've merged it into epsilon.
