### ISSUE TITLE
Content from the Website

### ISSUE THREAD

**Issue by amstan** [aichallenge/aichallenge#61]
I have to move over the stuff from the wiki written by antimatroid to the website using a markdown to html program.

**Comment by McLeopold** [comment]
It would be nice if the process was repeatable so that we could update the wiki, then push/pull the results to the website when desired.

**Comment by amstan** [comment]
Working on that now.
sudo apt-get install markdown seems to do exactly what i want.
Making a makefile for it.

Alexandru Stan

**Comment by amstan** [comment]
I finished making the script to add the stuff automatically from the wiki(with a little help).
You can review it at the test server: http://hypertriangle.com:13080/problem_description.php
