### ISSUE TITLE
nightly build system

### ISSUE THREAD

**Issue by McLeopold** [aichallenge/aichallenge#64]
Setup nightly builds to ensure code checked in is function.  Preferably make it setup a running instance of the contest.  Maybe buildbot? http://trac.buildbot.net/

**Comment by amstan** [comment]
I setup a dedicated server for testing the contest: http://hypertriangle.com:13080/
Contact me if you need an account.

Actually making a buildbot would require me to get something like an uninstall script. Buildbot also needs tests, and that also requires time(which could be better spent in fixing bugs).

Reopen it if you really want more.
