### ISSUE TITLE
ants.py has a bug with score distribution

### ISSUE THREAD

**Issue by hbhasker** [aichallenge/aichallenge#69]
This code doesn't check if enemies is empty before calling Fraction(). It
throws a DivideByZero exception.
Commit id: 508db7cb0ec8153321a4186f64b2d583396ee810
-        # distribute score for ants which died from collisions
-        for ant in colliding_ants:
-            # find living nearby enemies
-            enemies = self.nearby_ants(ant.loc, self.attackradius, ant.owner)
-            # in addition to the living nearby enemies, dead nearby enemies 
-            #   should get points too!
-            for other_ant in colliding_ants:
-                # only interested in enemies within range
-                if other_ant.owner != ant.owner and self.distance(ant.loc, other_ant.loc) <= self.attackradius:
-                    enemies.append(other_ant)
-            score = Fraction(1, len(enemies))
-            for enemy in enemies:
-                self.score[enemy.owner] += score
  +

Sample stack trace:

Traceback (most recent call last):
  File "../worker/engine.py", line 157, in run_game
    game.finish_turn()
  File "/Users/bhasker/Projects/aichallenge/ants/ants.py", line 1015, in finish_turn
    self.do_orders()
  File "/Users/bhasker/Projects/aichallenge/ants/ants.py", line 512, in do_orders
    score = Fraction(1, len(enemies))
  File "/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/fractions.py", line 98, in **new**
    raise ZeroDivisionError('Fraction(%s, 0)' % numerator)
ZeroDivisionError: Fraction(1, 0)

**Comment by sigh** [comment]
Thanks, fixed now.
