### ISSUE TITLE
Multi Opponent Rankings & Matchings

### ISSUE THREAD

**Issue by amstan** [aichallenge/aichallenge#7]
Since now we have used bayeselo for rankings. But bayeselo can only handle 1v1 games with a binary state(win/loss) at the end. In order to have a 4 player game another rankings mechanism must be found.

[Forums Topic](http://ai-contest.com/forum/viewtopic.php?f=21&t=1234)

**Comment by amstan** [comment]
"&lt;j3camero&gt; I have just been chatting with dmj by email. He's got some delicious TrueSkill code for us. https://github.com/dmj111/trueskill"

I added his work as a submodule in the main repository.
Matching still have to be decided.

**Comment by stephen-smith** [comment]
McLeopold has imported the delicious trueskill code into the epsilon-new-schema branch and I'm working on providing some code to generate matches based on [TrueSkill Matchmaking](https://github.com/aichallenge/aichallenge/wiki/TrueSkill-Matchmaking).

**Comment by amstan** [comment]
stephen-smith: I see you added the matchmaking stuff in the manager/ folder. How finished is this?
Can you replace https://github.com/aichallenge/aichallenge/blame/epsilon/manager/trueskill_matchups.pywith https://github.com/aichallenge/aichallenge/blame/epsilon/manager/trueskill_matchups.py ?

**Comment by amstan** [comment]
stephen-smith: I see you also have a branch with some matchmaking changes. Is that to be merged?

**Comment by stephen-smith** [comment]
The stuff in my branch should be working, test in a toy database locally before I push.  But, it is does not yet implement the Future Plans on the wiki.  I believe my earlier work was merge and is what is in the tree already.  I plan on opening a new merge request when I've covered everything in the Future Plans on the wiki.

Tonight, I'll check for merge conflicts with aichallenge/epsilon-new-schema and resolve them, probably by rebasing and retesting.

You links didn't work for me so I'm not sure if that replacement you proposed is sound.

**Comment by McLeopold** [comment]
The database schema has been changed to use TrueSkill.  Even though there are still issues with ranking, I'm closing this and suggesting specific issues/bugs be opened as new issues with more detail.
