### ISSUE TITLE
ants.py engine must read bots stderr output

### ISSUE THREAD

**Issue by hbhasker** [aichallenge/aichallenge#70]
Ants.py doesn't read the bots stderr, so if the bots writes logs out to stderr the write to stderr
will eventually block causing the bot to time out.

**Comment by sigh** [comment]
There is now a --log_stderr option for playgame.py. If it is "file" the bot's stderr is logged to output_dir, if it is "stderr" it is logged to the terminal stderr, otherwise it is ignored. By default the value is "stderr".
