### ISSUE TITLE
Integrate ants visualizer into the website 

### ISSUE THREAD

**Issue by amstan** [aichallenge/aichallenge#78]
Integrate ants @mleise's visualizer into the website.
Make sure it's easy to use as a widget, so it can be embedded in index.php.

**Comment by mleise** [comment]
A browser detection is required to load either the applet or the html canvas visualizer. Other than that it should be ready to use on any page in any quantity.

**Comment by amstan** [comment]
Seems to work pretty well: http://hypertriangle.com:13080/visualizer.php?game_id=1
I'm going to work on a widget now.
