### ISSUE TITLE
Internet Explorer compatibility for the canvas visualizers

### ISSUE THREAD

**Issue by mleise** [aichallenge/aichallenge#8]
I ignorantly assumed that IE 8 has <i>some kind</i> of canvas support, but when I checked yesterday I realized it doesn't. How are these IE users supposed to view the replays? It would be possible to write a Java applet from scratch, give them a hint to use a different browser or use Google's excanvas which generates vml (vector markup language) elements for every draw command, effectively emulating the canvas element. But it lacks some features, notably text output.

Current share of Internet Explorer users on ai-contest.com:
1.24% use IE 7 or older
4,21% use IE 8

**Comment by flagcapper** [comment]
I'm not sure people will agree with me on this, but it's probably not necessary to support a browser that a relatively small number of programmers actually use. If it's really an issue, we can tell them that they need to install something like Google Chrome Frame:

http://code.google.com/chrome/chromeframe/

**Comment by mleise** [comment]
I am now writing a Java wrapper that exports the HTML canvas interface into JavaScript.

**Comment by mleise** [comment]
Well eventually I also wrapped the whole JavaScript execution in Java. That turned out to be faster and as a side effect produced an offline-visualizer with the same features.
