### ISSUE TITLE
IE support for the website

### ISSUE THREAD

**Issue by amstan** [aichallenge/aichallenge#80]
I still have to check how IE and Opera handle the new website design.

**Comment by amstan** [comment]
Opera's good now.
IE has big problems, i need someone with a windows comp to help me on this one.

**Comment by amstan** [comment]
@Frontier: Is it all good now?

**Comment by mleise** [comment]
Java: check
IE9 + canvas: check (the shadow effect on the big title text "google ai challenge" is not displayed)
older IEs: ???

**Comment by amstan** [comment]
According to browsershots IE8 seems to handle the my css alright, but it seems to not like your visualizer.
