### ISSUE TITLE
Bots can't see end of game info because they are stopped

### ISSUE THREAD

**Issue by sigh** [aichallenge/aichallenge#95]
Bots currently only run when we let them (and we can time them). This means that when the game ends, they don't get to see the end of game info.

There are a few things we can do here:
1. Ignore it. In this case there is no point sending info to the bots after the game ends, and we should remove that part of the spec.
2. Let the bots run a bit. After the game ends, we give each bot a bit of time to clean up. This seem wasteful in production.
3. Have an optional non-strict mode which won't pause the bots. This means that the problem goes away when people are running locally (assuming this info only matters for local dev).

Thoughts?

**Comment by McLeopold** [comment]
A flag should be passed to the engine that allows the bots to be started up at the end of the game and sent ending information.  This would be used for local testing/training only.  The official workers would not pass this flag, therefore the bots would just be killed.  I currently have severe changes in progress on the engine in the epsilon-io branch, so I will add the flag in the next day or so and then merge back.

**Comment by McLeopold** [comment]
Fixed in the last week or so.
