### ISSUE TITLE
Visualizer Links

### ISSUE THREAD

**Issue by McLeopold** [aichallenge/aichallenge#98]
The visualizer needs to make player names clickable from the replay metadata.  The recent changes as of Cinco de Mayo now add the appropriate data to make this possible.

**Comment by aerique** [comment]
I can't really test this but going through the source I wonder whether this might already have been fixed?

If you check `visualizer/js/Application.js` lines 544 to 564 there's this function:

``` javascript
buttonAdder = function(i) {
    var color = vis.replay.htmlPlayerColors[i];
    var func = null;
    if (vis.replay.meta['user_url'] && vis.replay.meta['user_ids']
            && vis.replay.meta['user_ids'][i]) {
        func = function() {
            window.location.href =
                    vis.replay.meta['user_url'].replace('~',
                            vis.replay.meta['user_ids'][i]);
        };
    }
    var caption = vis.replay.meta['playernames'][i];
    if (ranks[i] === 1) {
        caption = '★ ' + caption;
    } else if (ranks[i] === 2) {
        caption = '☆ ' + caption;
    } else {
        caption = ranks[i] + '. ' + caption;
    }
    bg.addButton(caption, color, func);
}
```

which seems to make the player name clickable when `user_url` and `user_ids` is available in the replay file.

**Comment by McLeopold** [comment]
Frontier mentioned on IRC that this had always been working, so I don't think it needs attention.  But, let's leave this open until when hit beta, as the json may still change up until that point.
